### ISSUE TITLE
Regression with constraints produced by Nullable

### ISSUE THREAD

**Issue by gusty** [dotnet/fsharp#11344]
**Repro steps**

Run the following in fsi:

```
open System

type JsonValue = JNull

type JsonEncoding = JsonEncoding with
    static member nullableE encoder (x: Nullable<'a>) = if x.HasValue then encoder x.Value else JNull
    static member nullable  codec = JsonEncoding.nullableE codec
```

**Expected behavior**

Compile OK

**Actual behavior**

```
~vs3D37.fsx(7,37): error FS0193: Type constraint mismatch. The type 
    ''a'    
is not compatible with type
    'Nullable<'a>'    
```

**Known workarounds**

 - Don't upgrade Visual Studio
 - Transform the first method to a let bind

**Related information**

* Operating system: Windows
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Works in VS 16.8.3, doesn't work in VS 16.9.3

**Comment by cartermp** [comment]
Only speculative, but https://github.com/dotnet/fsharp/pull/10582 may be related, since this was the only tweak that I know of from VS 16.8 until VS 16.9. Confirmed that the old code used to work, but now does not.

**Comment by cartermp** [comment]
cc @tihan, @dsyme

**Comment by TIHan** [comment]
I can confirm that https://github.com/dotnet/fsharp/pull/10582 is what caused this regression. Am looking at this.
