### ISSUE TITLE
When run in FSI, FsiEvaluationSession throws exception when evaluating expression

### ISSUE THREAD

**Issue by CosminSontu** [dotnet/fsharp#14622]
Issue Description:

Trying to go through Tutorial: Hosted Execution from fsharp.github.io (https://fsharp.github.io/fsharp-compiler-docs/fcs/interactive.html).
Basically trying to start a FsiEvaluationSession and evaluate f# code.

Steps required to reproduce the problem:

1. Start Repl (either Visual Studio 2022's repl or dotnet fsi has the same outcome)
2. Send tutorial code snippets to fsi
3. When the following line is evaluated,
_evalExpression "42 + 1"_
FsiEvaluationSession throws an exception:

_> evalExpression "42 + 1";;
FSharp.Compiler.Interactive.Shell+FsiCompilationException: Operation failed. The error text has been printed in the error stream. To return the corresponding FSharpDiagnostic use the EvalInteractionNonThrowing, EvalScriptNonThrowing or EvalExpressionNonThrowing
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.commitResult[a,b](FSharpChoice`2 res) in D:\a\_work\1\s\src\Compiler\Interactive\fsi.fs:line 3418
   at FSI_0032.evalExpression(String text)
   at <StartupCode$FSI_0033>.$FSI_0033.main@()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Stopped due to error_

when looking at error stream I find the following output:

_> printf "%A" errStream;;

**error FS0193: internal error: The thread is already executing the ControlledExecution.Run method.**_

**Expected behavior**

Of course the expectation is that FSIEvaluationSession wouldn't throw exception when tutorial is performed 
in FSI (Assumption based on the fact that fsi #r directive is used in tutorial code samples).

Otherwise (hopefully not), please add note in the tutorial itself stating fsi is not a supported environment for FsiEvaluationSession.

**Actual behavior**

when evaluating a code snipet via any FsiEvaluationExpression eval methods, the following exception ends its execution:
**_error FS0193: internal error: The thread is already executing the ControlledExecution.Run method._**

**Known workarounds**

_Compiling the tutorial code samples as F# Console App works fine!_
Couldn't find any  workaround for successful execution in FSI.

**Related information**
Using the following reference of F# Compiler Services:
 #r "nuget: FSharp.Compiler.Service, 42.7.101"

* Operating system
Windows 11
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
_- fsi;;
val it: FSharp.Compiler.Interactive.InteractiveSession =
  FSharp.Compiler.Interactive.InteractiveSession
    {CommandLineArgs = [|"C:\Program Files\dotnet\sdk\7.0.102\FSharp\fsi.dll"|];_
* Editing Tools (e.g. Visual Studio Version, Visual Studio)
Same behavior from both VS F# Interactive window and dotnet fsi

**Comment by KevinRansom** [comment]
This is quite meta --- but it should work.  I'm sure it used to work.  However, I can sort of imagine how it would fail now.

**Comment by nhirschey** [comment]
In net7.0 versions of FSharp.Formatting, I get the same error trying to use the library from a script. FSharp.Formatting is calling `fsiSession.EvalInteraction(sprintf "#load @\"%s\"" path)` behind the scenes and that's what throws the error on `FSharp.Formatting.Literate/Evaluator.fs:line 371`

Here is dotnet 7.0.102. Below I show the same code working with dotnet 5.0.406

### 7.0.102
```fsharp
#r "nuget: FSharp.Formatting, 17.*"
open FSharp.Formatting.Literate
open FSharp.Formatting.Literate.Evaluation
open FSharp.Formatting.Markdown

// Sample literate content
let content =
    """
let a = 10
(*** include-value:a ***)"""

// Create evaluator and parse script
let fsi = FsiEvaluator()

let doc = Literate.ParseScriptString(content, fsiEvaluator = fsi)

Literate.ToHtml(doc)
> 
Error establishing FSI:
input.fsx (1,1)-(1,1) interactive error internal error: The thread is already executing the ControlledExecution.Run method.

Exception: FSharp.Compiler.Interactive.Shell+FsiCompilationException: Operation could not be completed due to earlier error
FSharp.Compiler.Interactive.Shell+FsiCompilationException: Operation could not be completed due to earlier error
   at FSharp.Formatting.Literate.Evaluation.FsiEvaluator..ctor(FSharpOption`1 options, FSharpOption`1 fsiObj, FSharpOption`1 addHtmlPrinter, FSharpOption`1 discardStdOut, FSharpOption`1 disableFsiObj, FSharpOption`1 onError) in /home/runner/work/FSharp.Formatting/FSharp.Formatting/src/FSharp.Formatting.Literate/Evaluator.fs:line 371
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in C:\Users\nicho\Untitled-1:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Stopped due to error
```
### 5.0.406

```fsharp
#r "nuget: FSharp.Formatting, 14.*"

open FSharp.Formatting.Literate
open FSharp.Formatting.Literate.Evaluation
open FSharp.Formatting.Markdown

// Sample literate content
let content =
    """
let a = 10
(*** include-value:a ***)"""

// Create evaluator and parse script
let fsi = FsiEvaluator() 

let doc = Literate.ParseScriptString(content, fsiEvaluator = fsi)

Literate.ToHtml(doc)
> 
val content : string = "
let a = 10
(*** include-value:a ***)"
val fsi : FsiEvaluator
val doc : LiterateDocument
val it : string =
  "<table class="pre"><tr><td class="lines"><pre class="fssnip">"+[459 chars]

```

**Comment by KevinRansom** [comment]
Hi,

this issue was fixed by this PR:  https://github.com/dotnet/fsharp/pull/15184 it will be part of the VS2022 17.7 release.

The issue is caused because fsi creates an ControlledExecution thread to enable ctrl+c handling in interactive, Controlled execution blocks are not recursive, and so once there is one on a thread while executing inside it, no further ControlledExecution blocks can be added.

The change insures that if --non-interactive is specified then no further ControlledExecutions are created.  Which will fix the behaviour.

Thanks

Kevin
