### ISSUE TITLE
FSharp - Compiler crashes if an anonymous record passed as obj argument

### ISSUE THREAD

**Issue by livarcocc** [dotnet/fsharp#7466]
@AkosLukacs commented on [Wed Aug 28 2019](https://github.com/dotnet/sdk/issues/3586)

The FSharp compiler's issue was reported FSharp repo: https://github.com/dotnet/fsharp/issues/6434, and is fixed, and does work with 3.0.100-preview8-013656.
But doesn't work with SDK 2.2.401, I guess the compiler fix isn't in 2.2.401. Do you plan on releasing new version for 2.2?

Repro: 
> dotnet new console -lang F#

```fsharp
// Program.fs, stolen from Vasily
let foo (_: obj) = ()

let bar() = foo {| F = 1 |}

[<EntryPoint>]
let main argv =
    bar()
    0
```

> dotnet run

# 2.2.401
Fails `error FS0192 : internal error : the anonymous record <>f__AnonymousType951611317`1' has not been generated in the pre-phase of generating this module`
 - Failed before I installed v3 preview
 - Did work after installing v3 preview
 - Failed to compile again after creating global.json and setting sdk version to 2.2.401

# 3.0.100-preview8-013656
Works as expected

**Comment by cartermp** [comment]
@livarcocc I asked for this issue to be filed on the SDK side because it's about taking an updated F# compiler. We've fixed this quite a while ago, and it's even fixed in the 16.2 update. But for some reason the corresponding SDK doesn't have that compiler.

**Comment by livarcocc** [comment]
That's up to the FSharp team to push an updated compiler.

**Comment by cartermp** [comment]
Sounds like more confusion around shipping then 😢 

@KevinRansom @brettfo what can we do here?

**Comment by livarcocc** [comment]
We would need the compiler in release/2.2.4xx and release/2.1.8xx. Though, at this point, we missed the September release already. We can maybe take it for October.

**Comment by cartermp** [comment]
Closing as this has long been resolved
