### ISSUE TITLE
The --langversion error text is not that useful

### ISSUE THREAD

**Issue by 0x53A** [dotnet/fsharp#9019]
I wanted to use the new LangVersion feature and added ``<LangVersion>4.6</LangVersion>``.

This caused an error: ``FSC : error FS0246: Unrecognized value '4.6' for --langversion use --langversion:? for complete list``.

How is a user supposed to do that? I can't (easily) call fsc directly, it is always invoked through msbuild.

---
  
Then I thought I was smart and changed it to ``<LangVersion>?</LangVersion>`` in the project file.
On save, my VS closed. When I reopened the solution, VS also immediately closed again.
I assume there is a Process.Exit somewhere :D
(Edit: found it: https://github.com/dotnet/fsharp/blob/be621d8725e3ea88cb832f4d457bc0bf377172ed/src/fsharp/CompileOptions.fs#L845)

---

This is with VS 16.4.5 and .net sdk 3.1.101.

For comparison, the C# error is equally useless: ``error CS1617: Invalid option '12.34' for /langversion. Use '/langversion:?' to list supported values.``.

**Comment by 0x53A** [comment]
The error is caused by the language dependant parsing, ``<LangVersion>4,6</LangVersion>`` works: https://github.com/dotnet/fsharp/issues/7757

**Comment by 0x53A** [comment]
Also, unrelated, would it be possible to create git tags for .net sdk versions, just like the Visual Studio versions?

This was fixed by https://github.com/dotnet/fsharp/pull/7895 and merged into master on November 22, but seems to be NOT included in .NET SDK 3.1.101 which was released January 14.

**Comment by cartermp** [comment]
@0x53A VS 16.4 is no longer considered supported, can you upgrade to VS 16.5.x? This will also include an updated .NET Core SDK, since 3.1.101 is similarly old. I confirmed this works with 3.1.201, which ships alongside VS 16.5.

As for your question about git tags - probably not. The SDK releases far too frequently with patches, and it's just an automated system that takes our package and incorporates it. Generally speaking it's the same compiler as what ships in VS, since all SDKs are now aligned with a given VS release. Aside from exceptional circumstances like big security problems, the compiler isn't any different. With VS, we still need to be intentional about the build that is picked for inclusion, so it's pretty simple to tag it.

**Comment by 0x53A** [comment]
Hi @cartermp, 

I mixed a few things together in the issue.

1) I updated VS and the parsing bug was fixed, as expected

2) **My main intention with this issue was to recommend to change the error text** and include the supported versions, because it is not always trivial to execute ``fsc --langversion:?``. For VS, I can open the _visual studio developer command prompt_. But there does not seem to be an easy way to execute fsc from the .net sdk? I tried ``dotnet fsc``, but that does not exist.

3) Even with VS 16.5.4, it still closes if you set ``<LangVersion>?</LangVersion>``, but tbh thats more of a funny easter egg than a real bug.

Thanks
