### ISSUE TITLE
`FSharp.Core` isn't implicitly defined after upgrading to 7.0.201

### ISSUE THREAD

**Issue by omppye** [dotnet/fsharp#14823]
I have a large codebase using central package management and when I upgraded .NET version from v7.0.102 to v7.0.201 this error started to throw up

```sh
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
  Determining projects to restore...
  Restored /Users/omppye/repos/repro-fsharp-1/Repro.fsproj (in 93 ms).
/Users/omppye/repos/repro-fsharp-1/Program.fs(3,9): error FS3353: Feature 'string interpolation' requires the F# library for language version 5.0 or greater. [/Users/omppye/repos/repro-fsharp-1/Repro.fsproj]

Build FAILED.

/Users/omppye/repos/repro-fsharp-1/Program.fs(3,9): error FS3353: Feature 'string interpolation' requires the F# library for language version 5.0 or greater. [/Users/omppye/repos/repro-fsharp-1/Repro.fsproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.20
```

**Reproduction steps**

Just clone [https://github.com/omppye/repro-fsharp-1](https://github.com/omppye/repro-fsharp-1) and try to build using .NET v7.0.201

**Expected behavior**

Build as usual like in the v7.0.102

**Comment by KevinRansom** [comment]
CentralPackageManagement is not really compatible with automatically taking an updated library.
However in the targets.props of your repo 
set DisableImplicitSystemValueTupleReference 
and DisableImplicitFSharpCoreReference to false

That should cause the implicit version to be computed and included.

I hope this helps,

Kevin

**Comment by omppye** [comment]
It worked well, thanks!
Do you have any thoughts on how the version upgrade affected this anyway?

**Comment by KevinRansom** [comment]
In this release we added direct support for CentralPackageManagement to disable ImplicitReference of FSharpCore.  The change you just made disabled that.
