### ISSUE TITLE
F# 10 - Class hierarchy employing CRGP now produces compile error FS0193

### ISSUE THREAD

**Issue by jwosty** [dotnet/fsharp#19037]
A certain code pattern utilizing CRGP (*[Curiously Recurring Generic Pattern](https://blog.stephencleary.com/2022/09/modern-csharp-techniques-1-curiously-recurring-generic-pattern.html)*) which successfully compiles under the F# 9 compiler no longer compiles under the F# 10 compiler.

In the real scenario, I encountered this with a type hierarchy implementing `IEquatable<'T>`.

**Repro steps**

1. Create an F# library project. Paste the following into `Library.fs`:

```fsharp
module MyModule

type IFoo<'T when 'T :> IFoo<'T>> =
    abstract member Bar: other:'T -> unit

[<AbstractClass>]
type FooBase() =
    
    interface IFoo<FooBase> with
        member this.Bar (other: FooBase) = ()

[<Sealed>]
type FooDerived<'T>() =
    inherit FooBase()
    
    interface IFoo<FooDerived<'T>> with
        member this.Bar other = ()

type IFooContainer<'T> =
    abstract member Foo: FooDerived<'T>

let inline bar<'a when 'a :> IFoo<'a>> (x: 'a) (y: 'a) = x.Bar y
let inline takeSame<'a> (x: 'a) (y: 'a) = ()

// Successfully compiles under .NET 9 + F# 9
// Error under .NET 10 + F# 10: Program.fs(26,13): Error FS0193 : The type 'FooDerived<'TId>' does not match the type 'FooBase'
let callBar_NewlyBroken (foo1: IFooContainer<'TId>) (foo2: IFooContainer<'TId>) =
    bar foo1.Foo foo2.Foo
    
// Successfully compiles under both versions
let callBar (foo1: IFooContainer<'TId>) (foo2: IFooContainer<'TId>) =
    let id1 = foo1.Foo
    let id2 = foo2.Foo
    bar id1 id2
```

2. Target .NET 9 in project and `global.json` (I tested under .NET SDK 9.0.111 + F# Compiler version 12.9.100.0 for F# 9.0)
3. Run `dotnet build`
4. Observe that the project builds successfully
5. Change target in project and `global.json` to latest .NET 10 preview (at the time of writing .NET SDK 10.0.100-rc.2.25502.107 + F# Compiler version 14.0.100.0 for F# 10.0)
6. Run `dotnet build`
7. Observe F# compile error: `Error FS0193 : The type 'FooDerived<'TId>' does not match the type 'FooBase'`

**Expected behavior**

Project should compile successfully

**Actual behavior**

The F# compiler produces an error: `Error FS0193 : The type 'FooDerived<'TId>' does not match the type 'FooBase'`

**Known workarounds**

Provide additional annotations, or introduce additional variable bindings to get type inference to succeed.

**Related information**

Provide any related information (optional):

* Operating system
* .NET SDK 10.0.100-rc.2.25502.107
* F# Compiler version 12.9.100.0 for F# 9.0
* Editing Tools (e.g. Visual Studio Version, Visual Studio)

**Comment by jwosty** [comment]
I've discovered an even simpler workaround. Oddly enough, this is enough to get it to compile:

```fsharp
    // ... snip ...
    let callBar_NewlyBroken (foo1: IFooContainer<'TId>) (foo2: IFooContainer<'TId>) =
        bar (foo1.Foo : _) foo2.Foo
```

**Comment by majocha** [comment]
I tried with rc2 and also some older net10.0 previews but had no success reproducing this. Hmm.

**Comment by jwosty** [comment]
@majocha Looks like I made a mistake when originally pasting the reproduction - try again now

**Comment by majocha** [comment]
Ok, got it. Still compiles in 10.0.100-preview.6.25358.103, fails in rc2

10.0.100-preview.7.25322.101 works

10.0.100-preview.7.25380.108 error FS0193: The type 'FooDerived<'TId>' does not match the type 'FooBase'

**Comment by majocha** [comment]
This is a bug in type subsumption cache key generation. Unsolved type variables should not be cached but they are.

**Comment by jwosty** [comment]
@majocha @T-Gro when will the fix make it to release? Bug still seems to repro in latest .NET SDK (10.0.101)

**Comment by T-Gro** [comment]
10.0.200 will be the NET SDK version with this fix.
