### ISSUE TITLE
internal error: multiple methods appear with identical argument types  

### ISSUE THREAD

**Issue by 0101** [dotnet/fsharp#17796]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Checkout [`lsp`](https://github.com/dotnet/fsharp/tree/lsp) branch
2. `build.cmd -c Debug` or just build `FSharp.Compiler.LanguageServer` project

**Expected behavior**

Build completes successfully

**Actual behavior**

We get 
```
error FS0192 : internal error : multiple methods named AddSingleton appear with identical argument types in type Microsoft.Extensions.DependencyInjection.ServiceCollectionSer
viceExtensions [D:\code\fsharp\src\FSharp.Compiler.LanguageServer\FSharp.Compiler.LanguageServer.fsproj]
```

**Related information**

Here's the code that triggers the error: https://github.com/dotnet/fsharp/blob/c1486be9a7db235018a27e8c3219309a10895891/src/FSharp.Compiler.LanguageServer/FSharpLanguageServer.fs#L46-L59

**Comment by vzarytovskii** [comment]
It might be caused by https://github.com/dotnet/fsharp/pull/16168 as well

**Comment by DedSec256** [comment]
Referenced `Microsoft.Extensions.DependencyInjection.Abstractions` contains two extension methods with the same name `AddSingleton` and parameters count, but different number of generics
```C# 
public static IServiceCollection AddSingleton<TService>(this IServiceCollection services)
public static IServiceCollection AddSingleton<TService, TImplementation>(this IServiceCollection services)
``` 

I think issue localized in this change from https://github.com/dotnet/fsharp/pull/17597

![{20B9EFCA-9D59-4A0F-BDB7-9D6D96988964}](https://github.com/user-attachments/assets/8e0a9f7d-217f-4b17-ad81-1db122540427)

which triggers additional call of `resolveILMethodRefWithRescope`, which doesn't take generics into account when searching for methods, and therefore returns an error. 


I managed to build the `FSharp.Compiler.LanguageServer` project locally after the revert of https://github.com/dotnet/fsharp/pull/17597

**Comment by T-Gro** [comment]
This makes sense Alex @DedSec256 , thanks. I will adjust that change.
Surprisingly, resolveILMethodRefWithRescope is not new a was already used at different places before.

**Comment by rstm-sf** [comment]
@T-Gro hello, could you tell how can check the fix? In RC2 I get something like this

**Comment by Thorium** [comment]
I'm having similar error after updating to latest VS2022 Prerelease v5,  9.0.100-rc.2.24474.11
In Prerelease 2.1 I didn't have this.
