### ISSUE TITLE
dotnet fsi not working on latest 5.0 nightly

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/fsharp#7369]
**Repro steps**

1. Install the latest nightly:

```
curl https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-linux-x64.tar.gz --output sdk.tgz && 
mkdir -p dotnet &&
tar xfz sdk.tgz -C dotnet/ &&
dotnet/dotnet fsi
```

2. Evaluate any expression:
```
> 1 + 1 ;;

  1 + 1 ;;
  ^

/home/eitsarpa/test/stdin(2,1): error FS0074: The type referenced through 'System.Decimal' is defined in an assembly that is not referenced. You must add a reference to assembly 'The system type 'System.Decimal' was required but no referenced system DLL contained this type'.
```
or
```
> typeof<System.DateTime> ;;

  typeof<System.DateTime> ;;
  --------------^^^^^^^^

/home/eitsarpa/test/stdin(3,15): error FS0039: The type 'DateTime' is not defined in 'System'.
```

The issue does not reproduce with the 3.0.1xx nightly

* Operating system: Ubuntu 18.04 & Windows 10
* .NET Core 5.0

**Comment by eiriktsarpalis** [comment]
I'm seeing other issue with the same bits, so I'm assuming this is attributable to 5.0 snafu. @cartermp should I close this?

**Comment by cartermp** [comment]
We can keep it open for now

**Comment by eiriktsarpalis** [comment]
The issue is reproducing with sdk version 3.1.100-preview1-014394 too.

**Comment by eiriktsarpalis** [comment]
Closing in favor of #7811
