### ISSUE TITLE
error FS0192 : internal error : unexpected non-generation of witness with FSharp.Core 5.0

### ISSUE THREAD

**Issue by marklam** [dotnet/fsharp#10472]
Code that previously compiled no longer builds with F# 5.0 and FSharp.Core 5.0

Perform a **debug** build of a .net5 class library with the code:
```FSharp
module Adapter =
    let inline clamp16 v = uint16 (max 0. (min 65535. v))
    let inline clamp8  v = uint8  (max 0. (min   255. v))

    type Clampage =
        static member inline FromFloat (_ : byte,   _ : Clampage) = fun (x : float) -> clamp8  x
        static member inline FromFloat (_ : uint16, _ : Clampage) = fun (x : float) -> clamp16 x

        static member inline Invoke (x: float) : 'Num =
            let inline call2 (a: ^a, b: ^b) = ((^a or ^b) : (static member FromFloat : _*_ -> _) (b, a))
            let inline call (a: 'a) = fun (x: 'x) -> call2 (a, Unchecked.defaultof<'r>) x : 'r
            call Unchecked.defaultof<Clampage> x
```

**Expected behavior**

Code compiles (which it does in release)

**Actual behavior**

error FS0192 : internal error : unexpected non-generation of witness 

**Known workarounds**

Set `/langversion:4:7` in build options or project file `<OtherFlags>`

**Related information**

* Windows 10
* .net 5
* Visual Studio 2019 16.8.1

Sample project:
[Thing.zip](https://github.com/dotnet/fsharp/files/5548863/Thing.zip)

**Comment by TIHan** [comment]
// cc @dsyme

**Comment by dsyme** [comment]
@marklam Note that setting `/langversion4:7` allows a workaround

**Comment by marklam** [comment]
@dsyme Thanks.

**Comment by TysonMN** [comment]
> **Known workarounds**
> 
> Set `/langversion:4:7` in build options or project file `<OtherFlags>`

In the case of project file `<OtherFlags>`, the specific notation for the workaround is `--langversion:4.7`.  The whole line is
```xml
<OtherFlags>--langversion:4.7</OtherFlags>
```

**Comment by smoothdeveloper** [comment]
Also hit on https://github.com/smoothdeveloper/zcore-midi-fs it comes with a long stack trace of the compiler eventually reaching this instance of the message:

https://github.com/dotnet/fsharp/blob/b23b2a0f99f12ece94c5ad89aabb9169d51091f3/src/fsharp/IlxGen.fs#L3137-L3146

**Comment by gusty** [comment]
I'm also facing this error in a production project which I can't share.

Setting lang to 4.7 is annoying as we want to take advantage of new features.

**Comment by cartermp** [comment]
Just for posterity you don't need `OtherFlags` and I would recomment using `<LangVersion>` property instead.

@dsyme would you be able to take a look here?

**Comment by gusty** [comment]
@dsyme What's the status on this? Why Backlog?

I was hoping this issue to get prioritized as it's a regression, and it's preventing us to move to our new libraries which use F# 5.0

I still really hope you can find a fix soon.

**Comment by dsyme** [comment]
There's a fix coming in https://github.com/dotnet/fsharp/pull/11349

**Comment by TysonMN** [comment]
FWIW, I have confirmed that this issue is fixed when using Visual Studio 16.10 and FSharp.Core 5.0.1
