### ISSUE TITLE
Change in 4.7.0: Redundant `new` no longer reported

### ISSUE THREAD

**Issue by milbrandt** [dotnet/fsharp#7876]
Code analysed with latest FSharpLint, Nuget version 0.12.5

When all projects are build with _FSharp.Core 4.6.2_ message "FL0014: Usage of `new` keyword here is redundant." is reported twice when instances are created which does not implement `IDisposable`.
Only updating to _FSharp.Core 4.7.0_ the redundancy is no longer reported.

**Repro steps**

- ~~https://github.com/jmecsoftware/sonar-fsharp-plugin Solution file `FsSonarRunner/FsSonarRunner.sln` (see branch: _feature/fsharp470_)~~
- Reduced example https://github.com/milbrandt/RedundantNewFSharp470

- Update Nuget _FSharp.Core_ from 4.6.2 to 4.7.0 in all 3 projects

- Unit test `RunLintInSource` fails as the issue _"FL0014: Usage of `new` keyword here is redundant."_ is no longer reported

**Expected behavior**

- On classes which does not implement `IDisposable` warning if they are instantiated with `new`

**Actual behavior**

- "FL0014: Usage of `new` keyword here is redundant." is no longer reported after update of FSharp.Core to 4.7.0

**Known workarounds**

no work around for running lint from an application (on command line the warning is still reported)

**Related information**

Provide any related information (optional):

* Windows 10
* .netcoreapp2.2 or  .netcoreapp3.0
* Visual Studio 2019, 16.3.9

In https://github.com/fsprojects/FSharpLint/issues/364 the other way round: Required 'new' keyword marked as redundant

**Comment by cartermp** [comment]
Perhaps I’m misunderstanding but this isnt a breaking change?

**Comment by milbrandt** [comment]
> Perhaps I’m misunderstanding but this isnt a breaking change?
> …

The behavior changed from 4.6.2 to 4.7.0. The unit tests are breaking when updating the nuget package.

**Comment by BentTranberg** [comment]
I was a bit puzzled too, so I tried to google the term _breaking change_, without getting much wiser. However, in this forum  and in relation to programming languages and compiler technology in general, I believe the term "breaking change" is typically used to describe a change in the way the compiler interprets the source, to the extent that it requires previously compilable source to be modified. A modification can be required because the compiler will no longer accept the source as valid, or will emit a warning, or will compile the source successfully but emit code that no longer produces the desired result. Breaking changes can be intentional, as a result of changing the language definition. If unit tests are broken, then that results in a _broken build_, not a breaking change. If some other product is affected, then we're just dealing with an _issue_.

**Comment by forki** [comment]
Well, independent of the classification of the issue. Which case did chanfe exactly? Can you reduce the example as much as possible? Would be interesting to understand the concrete issue.

**Comment by milbrandt** [comment]
As proposed by @forki I reduced the code to the failing unit test and removed a lot of the surrounding code. It can be found at https://github.com/milbrandt/RedundantNewFSharp470.
I'll update the description above to point to the reduced code.

**Comment by abelbraaksma** [comment]
I tried both old (VS 2017) and new (VS 2019) to get the warning, but it appears to be gone. It doesn't seem to matter what version of F# I'm referencing. Whatever version, the warning does not show. My guess is that this warning disappeared as part of an fsc update. Or I just don't understand the issue. I tried with:

```f#
// warning expected on redundant use of new
let x = new System.String('t', 100)
let y = new System.Decimal(12)
```

I had warning levels set to 5.

**Comment by cartermp** [comment]
@abelbraaksma are you using FSharpLint? VS and the compiler don't warn on an unnecessary `new`; it's a linting rule in FSharpLint.

@milbrandt thanks for the repro. Though I have to say I'm surprised by this, because FSharp.Core has nothing to do with the AST of source code, and FSharpLint operates on the AST structure. Upgrading FSharp.Core also doesn't change the underlying compiler used, therefore the underlying tree structure is also not changed.

**Comment by abelbraaksma** [comment]
@cartermp I thought I had seen the warning on usages of 'new', and just assumed it was from fsc. In the past I've used f#lint, perhaps it came from that. But present versions don't support msbuild, and you're right, I'm indeed not using it.

Sorry for the noise.

**Comment by milbrandt** [comment]
The problem still exists. Updating to FSharpLint to 0.13.1 didn't cange anything.
As soon as FSharp.Core is updated from.. to 4.7.0 the redundant new is no longer reported.
Any help would be welcom, as otherwise I'm rapped with 4.6.2.

**Comment by jgardella** [comment]
I investigated this a bit from the FSharpLint side: the root of the issue seems to be [here](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/Rules/Conventions/RedundantNewKeyword.fs#L24) where we are trying to check if a symbol implements `IDisposable`. In 4.6.2 this code works, but after updating to 4.7.0 the `Some _` case is hit (i.e. `(symbol.Symbol :? FSharpMemberOrFunctionOrValue)` is returning false now).

@cartermp Is this the correct way to go about checking if a symbol is implementing `IDisposable`? If so, any idea why this behavior would change going from 4.6.2 to 4.7.0?

**Comment by cartermp** [comment]
I'm not sure what the difference is with FSharp.Core, but it could be related to some data being carried in the binary that isn't there anymore. Since this is ultimately reflection into internals, something could have changed?

More to the point, I think the best thing to do is to expose `IsDisposableType` on `FSharpEntity`: https://github.com/dotnet/fsharp/blob/master/src/fsharp/symbols/Symbols.fs#L576

There's multiple ways to ultimately access that, but once way would be with a type test. This would mean another rev of the compiler service, though (cc @baronfel )

**Comment by baronfel** [comment]
I mean, if we have to do it we have to do it.  I just want to make sure we're making them deliberately. 👍

**Comment by dsyme** [comment]
@baronfel I'd be ok with exposing IsDisposableType.  Though I believe it is going to be possible to determine this using the existing FCS API.  I don't see anything specifically wrong with that FSharpLint code however

**Comment by milbrandt** [comment]
Tested today with FSharp.Core 5.0.0 and still not reported.

**Comment by psfinaki** [comment]
So errh regardless of the fact if it worked or not - it doesn't work now. I'll close this in favor of this one as a duplicate: https://github.com/dotnet/fsharp/issues/2266
