### PR TITLE
Diagnose or hoist NativePtr.stackalloc where localloc is invalid IL

### LINKED ISSUE #20295: Diagnostic for `NativePtr.stackalloc` in positions where `localloc` can never be valid IL
The following snippets are accepted by the F# compiler but throw `System.InvalidProgramException` at load, before any user code runs. Follow-up to #8083 (general case fixed by #20302).

**1. `localloc` in an exception handler**

```fsharp
open Microsoft.FSharp.NativeInterop
try () with _ -> NativePtr.stackalloc<int> 1 |> ignore
```

**2. `localloc` while `this` is uninitialized (chained base constructor)**

```fsharp
open Microsoft.FSharp.NativeInterop
type A(p: nativeptr<int>) = class end
type B() = inherit A(NativePtr.stackalloc<int> 1)
B() |> ignore
```

Suggest rejecting them in `PostInferenceChecks` (dsyme's suggestion on #8083) — a compile-time error instead of an `InvalidProgramException` at JIT time.

<details>
<summary>Details</summary>

Fixed for the general case by #20302: `IlxGen` spills the pending stack, emits `localloc` at an empty stack, then reloads the pending values under the result pointer.

**Case 1 (handler).** The CoreCLR importer rejects `localloc` when `block->hasHndIndex()` (`dotnet/runtime`, `jit/importer.cpp`) — that is, inside a `catch`, `finally`, or `filter` handler, not a `try` body. This is why the `for .. in seq` shape in fsharp/fslang-suggestions#1469 works. `eenv.withinSEH` does not yet separate a handler from a `try` body, so the diagnostic needs a new flag.

**Case 2 (uninitialized `this`).** ECMA forbids spilling an uninitialized `this`, so `EmitLocallocCode` falls back to a plain emit when `uninitializedThisOnStackCount > 0`. The code is a use-after-free regardless: the stack memory dies when the constructor returns. A real fix, instead of a diagnostic, would hoist the base-constructor arguments into locals before `this` is pushed.

</details>

### PR DESCRIPTION
**Pull request by T-Gro**
Fixes #20295

- `NativePtr.stackalloc` inside the `with` handler, filter or `finally` block of a `try` (directly or via an inlinable lambda) now reports error FS3916 instead of emitting a `localloc` that the runtime rejects with `InvalidProgramException` at method load.
- `NativePtr.stackalloc` passed as a chained base-constructor argument no longer produces an assembly that throws `InvalidProgramException`; the base-constructor arguments are hoisted into locals before the uninitialized `this` is pushed.

### CODE REVIEW

**Review by T-Gro — COMMENTED** [review]
🤖 🕵️ LGTM

File: src/Compiler/TypedTree/TypedTreeOps.FreeVars.fs [hunk 1]
```diff
@@ -492,6 +492,46 @@ module internal FreeTypeVars =
...
+                pairs
+            else
+                // 'a' must precede 'b' when b's subtype constraint references a's parameter.
+                let mustPrecede (_, stamp, _) (_, _, deps) =
+                    match stamp with
+                    | ValueSome s -> Set.contains s deps
+                    | ValueNone -> false
+
+                nodes
+                |> List.stableTopologicalSort mustPrecede
```
Comment (abonie) [inline src/Compiler/TypedTree/TypedTreeOps.FreeVars.fs:532]: 🤖🕵️ This ordering rejects a call that succeeds under `--langversion:10.0`. The repro below compiles with `'u = int` under 10.0, but under 11.0 it infers `'u = string` and reports FS0001: `One` is incompatible with `I<string>`.

```fsharp
type I<'t> = interface end
type J<'t> = interface end
type One() =
    interface I<int>
type Many() =
    interface J<int>
    interface J<string>
type Outer<'t>() =
    member _.M<'a, 'b, 'c
        when 'a :> I<'b> and 'c :> J<'t>>() = ()
let test (outer: Outer<'u>) =
    outer.M<One, 'u, Many>()
```

The batch sort produces `[b; c; a]`: `c` checks the ambiguous interface before `a` establishes that the shared caller parameter is `int`. Select one ready node at a time and reconsider readiness, preserving `[b; a; c]` here, and add this regression case.

File: src/Compiler/CodeGen/IlxGen.fs [hunk 2]
```diff
@@ -5601,6 +5664,13 @@ and GenAsmCode cenv cgbuf eenv (il, tyargs, args, returnTys, m) sequel =
         && ilReturnTys |> List.forall (fun ty -> ty <> ILType.Void)
         ->
 
+        // The JIT rejects 'localloc' inside an exception-handling region, producing an
+        // InvalidProgramException at method load. By this point inlining and closure conversion have run,
+        // so eenv.withinExnHandler reflects the true handler region: an escaping closure carrying the
+        // 'localloc' into its own method has had the flag reset and stays legal.
+        if eenv.withinExnHandler then
+            errorR (Error(FSComp.SR.chkNativePtrStackallocInHandler (), m))
```
Comment (abonie) [inline src/Compiler/CodeGen/IlxGen.fs:5739]: 🤖🕵️ Optional inlining still turns a valid non-inline helper call into a compilation error. This runs with `--optimize-`, but reports FS3918 at `allocate ()` with `--optimize+`:

```fsharp
#nowarn "9"
open Microsoft.FSharp.NativeInterop
let allocate () = NativePtr.stackalloc<int> 1 |> ignore
let run () =
    try failwith "enter handler"
    with _ -> allocate ()
run ()
```

The shipping compiler throws `InvalidProgramException` for the optimized version, so this improves an existing failure rather than introducing a new runtime regression. Keep this final validity check, but prevent optional inlining from moving a callee's `localloc` into a prohibited handler region. Retaining the existing helper boundary preserves allocation lifetime, timing and exception propagation; rejecting direct or mandatory-inline handler allocations is a separate, necessary restriction.

Comment (T-Gro) [reply src/Compiler/CodeGen/IlxGen.fs]: This remains unaddressed by this task: I cannot safely change optional inlining while T-Gro/daily-monitor#882 retains unclear branch ownership. It entered `dm:recovery` at 2026-09-17 11:33 UTC and has not confirmed that branch-writing work has finished. I have left the branch and final FS3918 validity check untouched; this thread stays unresolved, with no fix or RED/GREEN verification claimed.

File: src/Compiler/TypedTree/TypedTreeOps.FreeVars.fs (hunk 1 above)
Comment (T-Gro) [reply src/Compiler/TypedTree/TypedTreeOps.FreeVars.fs]: At `457472851a7`, constraint ordering delegates to a shared sorter that still emits ready nodes in batches, so the outdated marker does not establish that this is fixed. I cannot safely start branch changes while T-Gro/daily-monitor#882 retains unclear ownership: it entered `dm:recovery` at 2026-09-17 11:33 UTC and has not confirmed that branch-writing work has finished. Leaving this unresolved; no fix or RED/GREEN verification is claimed.

Comment (T-Gro) [reply src/Compiler/TypedTree/TypedTreeOps.FreeVars.fs:532]: Fixed in 9c36f97b2e6455c56ae70efbada6b9783ccc91a9. The shared sorter now emits the first ready node and reconsiders the remaining order, giving `[b; a; c]` here while retaining independent-node order and original-order cycle recovery.

Your complete repro now infers `Outer<int> -> unit` under 10.0, 11.0 and preview. The retained baseline run reproduced FS0001 under 11.0/preview; the final Release tests pass on net11.0 and net472, including the newly-ready/dependent-chain cases and existing unsatisfied-constraint, overload and cycle controls.

File: src/Compiler/CodeGen/IlxGen.fs (hunk 2 above)
Comment (T-Gro) [reply src/Compiler/CodeGen/IlxGen.fs:5739]: Fixed in 9c36f97b2e6455c56ae70efbada6b9783ccc91a9. Optional inlining now retains the helper call when expansion would introduce a frame-local allocation into a catch, filter or finally region, including nested protected bodies and runtime quotation splices. Genuine method boundaries reset that restriction. The final IL validity check remains, and direct/mandatory-inline handler allocations still report FS3918; this fixes the shipping optimized failure rather than claiming a new runtime regression.

Your exact repro now compiles and runs with optimization off/on, with IL assertions confirming the retained call. Release tests passed on net11.0 and net472 for handler effects, exception identity, repeated helper-local allocations, cross-file/referenced helpers and all four quotation combinations; legal outside-handler inlining remains covered. The retained baseline reproduced FS3918, and the complete current-head [CoreCLR CI run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1600874) also passed.

File: src/Compiler/Optimize/Optimizer.fs [hunk 3]
```diff
@@ -4021,6 +4052,7 @@ and TryInlineApplication cenv env finfo (valExpr: Expr) (tyargs: TType list, arg
             | _ ->
                 let f2R = CopyExprForInlining cenv false f2 m
                 MakeApplicationAndBetaReduce g (f2R, f2ty, [tyargs], argsR, m)
+        if env.withinExnHandler && ExprMayHaveFrameLocalAllocation exprR then None else
```
Comment (abonie) [inline src/Compiler/Optimize/Optimizer.fs:4242]: 🤖🕵️ Handler-local non-inline helpers still lose their method boundary. On `9c36f97b2`, this compiles and runs with `--optimize-`, but fails with FS3918 under `--optimize+`:

```fsharp
#nowarn "9"
open Microsoft.FSharp.NativeInterop

let run () =
    try failwith "enter"
    with _ ->
        let allocate () = NativePtr.stackalloc<int> 1 |> ignore
        allocate ()

run ()
```

This guard protects `TryInlineApplication`, but `TryEliminateLet` → `TryEliminateBinding` can still beta-reduce the local helper into the handler. Apply equivalent boundary protection to that elimination path and add this case with optimization off/on. The original module-level example is fixed, but the boundary-preservation fix remains incomplete.

Comment (T-Gro) [reply src/Compiler/Optimize/Optimizer.fs:4260]: Done

File: src/Compiler/Optimize/Optimizer.fs [hunk 4]
```diff
@@ -1833,6 +1871,9 @@ let TryEliminateBinding cenv env bind e2 _m =
     elif vspec1.InlineInfo = ValInline.InlinedDefinition then None
     elif vspec1.LogicalName.StartsWithOrdinal stackVarPrefix ||
          vspec1.LogicalName.Contains suffixForVariablesThatMayNotBeEliminated then None
+    elif env.withinExnHandler &&
+         (let _, _, body, _ = stripTopLambda (stripDebugPoints e1, vspec1.Type)
+          ExprMayHaveFrameLocalAllocation body) then None
```
Comment (abonie) [inline src/Compiler/Optimize/Optimizer.fs]: 🤖🕵️ A leading `let` still hides the allocating lambda from this guard. On `ef867e144`, this compiles and runs with `--optimize-`, but fails with FS3924 under `--optimize+`:

```fsharp
#nowarn "9"
open Microsoft.FSharp.NativeInterop

let run () =
    try failwith "enter"
    with _ ->
        let allocate =
            let n = 1 + (System.Environment.TickCount &&& 1)
            fun () -> NativePtr.stackalloc<int> n |> ignore
        allocate ()

run ()
```

`stripTopLambda` stops at the outer `Expr.Let`, and the allocation detector skips the nested lambda; `MakeApplicationAndBetaReduceAux` subsequently traverses that same `let` and moves the allocation into the handler. Account for the leading bindings when checking the callable body, and cover this case with optimization off/on. The original direct-local-helper repro is fixed, but this boundary-preservation case remains broken.

File: src/Compiler/Utilities/illib.fs [hunk 5]
```diff
@@ -780,17 +780,14 @@ module List =
...
-                    remaining
-                    |> List.partition (fun x -> remaining |> List.forall (fun y -> not (mustPrecede y x)))
-                with
-                | [], cycle -> cycle
-                | ready, rest -> ready @ emit rest
+            let rec emitFirstReady skipped candidates =
+                match candidates with
+                | [] -> remaining
+                | x :: rest when remaining |> List.forall (fun y -> not (mustPrecede y x)) ->
+                    x :: emit (List.fold (fun acc y -> y :: acc) rest skipped)
```
Comment (abonie) [inline src/Compiler/Utilities/illib.fs]: 🤖🕵️ This introduces the inverse of the earlier constraint-ordering regression. With `--langversion:11.0`, base `e5462eb7` accepts this and infers `Outer<int> -> unit`, but head `ef867e144` selects `string` and reports FS0001: `One` is incompatible with `J<string>`:

```fsharp
type I<'t> = interface end
type J<'t> = interface end
type Many() =
    interface I<int>
    interface I<string>
type One() =
    interface J<int>
type Outer<'t>() =
    member _.M<'a, 'b, 'c
        when 'a :> I<'b> and 'c :> J<'t>>() = ()
let test (outer: Outer<'u>) =
    outer.M<Many, 'u, One>()
```

The new `[b; a; c]` order checks ambiguous `Many` before `One` establishes the shared caller parameter as `int`; the previous `[b; c; a]` order succeeds here. Preserve this case as well as the earlier counterexample, and add an assertion for the inferred `Outer<int> -> unit` signature.

**Review by abonie — COMMENTED** [review]
🤖🕵️ AI review — verify independently.

File: src/Compiler/Utilities/illib.fs (hunk 5 above)
Comment (abonie) [reply src/Compiler/Utilities/illib.fs]: Fixed in a47ed0bf1. Ready constraints are now ranked by feasible-supertype count before dependency ordering, so the unambiguous constraint establishes the shared caller parameter in both orderings. The regression asserts `Outer<int> -> unit`.

File: src/Compiler/Optimize/Optimizer.fs (hunk 4 above)
Comment (abonie) [reply src/Compiler/Optimize/Optimizer.fs]: Fixed in a47ed0bf1. Handler-local bindings now preserve the callable boundary when leading bindings hide a frame-local allocation, with optimization-off/on regression coverage.

File: src/Compiler/Optimize/Optimizer.fs [hunk 6]
```diff
@@ -1821,6 +1824,51 @@ let AddDirectDelegateTargetToDontInlineSet cenv env (slotsig: SlotSig) tmvs body
...
+
+let rec CallableExprMayHaveFrameLocalAllocation expr exprTy =
+    match stripDebugPoints expr with
+    | Expr.Let(_, body, _, _)
+    | Expr.LetRec(_, body, _, _)
+    | Expr.Sequential(_, body, NormalSeq, _) ->
+        CallableExprMayHaveFrameLocalAllocation body exprTy
+    | expr ->
+        let _, _, body, _ = stripTopLambda (expr, exprTy)
+        ExprMayHaveFrameLocalAllocation body
```
Comment (abonie) [inline src/Compiler/Optimize/Optimizer.fs]: 🤖🕵️ Computed local helpers still let `localloc` escape into the handler. On `c1947e15b`, this runs with `--optimize-`; with `--optimize+` it compiles successfully but throws `InvalidProgramException` when `run` loads:

```fsharp
#nowarn "9"
open Microsoft.FSharp.NativeInterop

let run () =
    try failwith "enter"
    with _ ->
        let allocate =
            if System.Environment.TickCount >= 0 then
                fun () -> NativePtr.stackalloc<int> 1 |> ignore
            else
                fun () -> NativePtr.stackalloc<int> 2 |> ignore
        allocate ()

run ()
```

`CallableExprMayHaveFrameLocalAllocation` handles leading `let`, `let rec`, and sequential expressions, but not the `Expr.Match` produced here. `StripPreComputationsFromComputedFunction` later distributes the call into those lambda targets, moving `localloc` into the handler without triggering FS3924. Inspect the same computed-function shapes that application reduction can consume, and add this case with optimization off/on.

**Review by abonie — COMMENTED** [review]
🤖🕵️ AI review — verify independently.

File: src/Compiler/Optimize/Optimizer.fs (hunk 6 above)
Comment (abonie) [reply src/Compiler/Optimize/Optimizer.fs]: Fixed in 81ef53513. The callable-body check now inspects both targets of the `Expr.Match` shape consumed by computed-function application reduction. The regression covers both leading-binding and conditional helpers with optimization off and on.

**Review by abonie — APPROVED** [review]
