### ISSUE TITLE
Compiler hangs wne compiling inline recursive invocation

### ISSUE THREAD

**Issue by miegir** [dotnet/fsharp#17376]
**Repro steps**
1. Create a new F# project with the following code in Program.fs:
``` F#
let rec inline test m = test m in test 0
```
2. Compile the project using `dotnet build`.

In fact, any recursive inline function can be declared and then invoked somewhere.

**Expected behavior**

Compiler is expected to output some error because inline rec functions are not allowed and quit.

**Actual behavior**

Compiler outputs several errors and warnings and then hangs with continuously increasing memory consumption. Compiler output before hang (with paths stripped):
```
Program.fs(1,25): error FS1114: The value 'test' was marked inline but was not bound in the optimization environment [TestApp.fsproj]
Program.fs(1,16): error FS1113: The value 'test' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible [TestApp.fsproj]
Program.fs(1,25): warning FS1116: A value marked as 'inline' has an unexpected value [TestApp.fsproj]
Program.fs(1,25): warning FS1118: Failed to inline the value 'test' marked 'inline', perhaps because a recursive value was marked 'inline' [TestApp.fsproj]
Program.fs(1,25): error FS1114: The value 'test' was marked inline but was not bound in the optimization environment [TestApp.fsproj]
Program.fs(1,16): error FS1113: The value 'test' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible [TestApp.fsproj]
Program.fs(1,25): error FS1114: The value 'test' was marked inline but was not bound in the optimization environment [TestApp.fsproj]
Program.fs(1,16): error FS1113: The value 'test' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible [TestApp.fsproj]
```

N.B. This bug is contrived of course. I never thought of writing such code in real applications.

**Comment by Martin521** [comment]
net8 compiles this without problems for me.
Which SDK / compiler / TFM are you using?

**Comment by Martin521** [comment]
Actually, after updating from 8.0.200 to 8.0.302 I have exactly the behavior described in the OP.
