### ISSUE TITLE
Compilation bug with FSharp.Core 4.5.1, works with 4.5.0

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#5390]
After upgrading from FSharp.Core 4.5.0 to 4.5.1, I get the following cryptic error when compiling in VS2017:

`E:\A\_work\80\s\src\fsharp\FSharp.Core\async.fsi(450,16): error FS0073: internal error: CodeGen check: type checking did not quantify the correct number of type variables for this method, #parentTypars = 1, #ctps = 1, #mtps = 0, #thisArgTys = 2`

Reverting to 4.5.0 fixes the problem. I have no idea what causes it, since none of my code is referenced in the error. Unfortunately I can't share the solution since it's a work project.

Let me know if I can provide further info.

**Comment by cmeeren** [comment]
Ah, a warning, I see. I have "treat warnings as errors" turned on, so this stops me from compiling.
