### PR TITLE
Do not use Unicode aware API and CurrentCulture in compiler

### PR DESCRIPTION
**Pull request by OwnageIsMagic**
Strictly speaking this is a breaking change, but it's for the good.
```fsi
// Unfortunately bold six '𝟲' U+1D7F2 is too bold to fit into Char.
// So let's speak some Farsi. Width nine, precision seven.
> printfn "%۹.۷f" 3. ;;









                                                                      3.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
val it: unit = ()

// NOTE: THIS IS NOT FIXED
// U+0B68 Oriya Digit Two
> let two = ୨UL ;;

  let two = ୨UL ;;
  ----------^^^

stdin(202,11): error FS1150: This number is outside the allowable range for 64-bit unsigned integers
```
Reverts https://github.com/dotnet/fsharp/pull/6524 cc @forki.
Part of https://github.com/dotnet/fsharp/issues/12352 (somewhat)

[RegexOptions.ECMAScript](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regexoptions#system-text-regularexpressions-regexoptions-ecmascript)

> For example, ECMAScript does not support language elements such as the Unicode category or block elements `\p` and `\P`. Similarly, the `\w` element, which matches a word character, is equivalent to the `[a-zA-Z_0-9]` character class when using ECMAScript and `[\p{Ll}\p{Lu}\p{Lt}\p{Lo}\p{Nd}\p{Pc}\p{Lm}]` when using canonical behavior.

[Choosing a `StringComparison` member for your method call](https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings#choosing-a-stringcomparison-member-for-your-method-call)
> File paths. A non-linguistic identifier, where case is irrelevant. `OrdinalIgnoreCase`

This PR is not comprehensive (there is at least [1 instance](https://github.com/dotnet/fsharp/blob/fb39b9440dd27f5ed093e0617cdce49d9dbffa3c/src/Compiler/Utilities/sformat.fs#L1531C48-L1531C60) of `Char.IsDigit` left).
Commits are logically separated, you can check each commit individually.

Fixed behaviour:
```fsi
> printfn "%۹.⅘f" 3. ;;

  printfn "%۹.⅘f" 3. ;;
  --------^^^^^^^

stdin(1,9): error FS0741: Unable to parse format string 'Bad format specifier: '۹''
```

### CODE REVIEW

File: src/Compiler/FSComp.txt [hunk 1]
```diff
@@ -236,7 +236,7 @@ forBadPrecision,"Bad precision in format specifier"
 forBadWidth,"Bad width in format specifier"
 forDoesNotSupportZeroFlag,"'%s' format does not support '0' flag"
 forPrecisionMissingAfterDot,"Precision missing after the '.'"
-forFormatDoesntSupportPrecision,"'%s' format does not support precision"
+forFormatDoesNotSupportPrecision,"'%s' format does not support precision"
```
Comment (vzarytovskii) [inline src/Compiler/FSComp.txt:239]: This rename will retrigger the whole translation pipeline which will take multiple weeks to translate in the best case scenario. Are we sure we want it?

File: src/Compiler/SyntaxTree/XmlDoc.fs [hunk 2]
```diff
@@ -320,14 +320,14 @@ type XmlDocumentationInfo private (tryGetXmlDocument: unit -> XmlDocument option
         )
 
     let tryGetSummaryNode (xmlDocSig: string) =
-        if xmlDocSig.Contains "'" && xmlDocSig.Contains "\"" then
+        if xmlDocSig.Contains ''' && xmlDocSig.Contains '\"' then
```
Comment (vzarytovskii) [inline src/Compiler/SyntaxTree/XmlDoc.fs:323]: The first will probably need escaping?

File: src/Compiler/Utilities/illib.fs [hunk 3]
```diff
@@ -78,6 +81,8 @@ module internal PervasiveAutoOpens =
         member inline x.EndsWithOrdinalIgnoreCase value =
             x.EndsWith(value, StringComparison.OrdinalIgnoreCase)
 
+    let inline isDigit (c: char) = (uint)(c - '0') <= (uint)('9' - '0');
```
Comment (vzarytovskii) [inline src/Compiler/Utilities/illib.fs:84]: Can you please make a comment why do we chose to use custom function instead of the one from Char?

**Comment by OwnageIsMagic** [comment]
2 tests are failed. Investigating...
```
E_MulticasePartialNotAllowed01_fs - --test:ErrorRanges(compilation: E_MulticasePartialNotAllowed01.fs)
Simple - W_BindCaptialIdent_fs - --test:ErrorRanges(compilation: W_BindCaptialIdent.fs)
```

File: src/Compiler/SyntaxTree/XmlDoc.fs (hunk 2 above)
Comment (OwnageIsMagic) [reply src/Compiler/SyntaxTree/XmlDoc.fs:323]: Yeah, but why it did compiled?

File: src/Compiler/FSComp.txt (hunk 1 above)
Comment (OwnageIsMagic) [reply src/Compiler/FSComp.txt:239]: Actually I was going to create another PR (rebase https://github.com/dotnet/fsharp/pull/2558), but got distracted. I can drop this for if it will cause troubles.

File: src/Compiler/Utilities/illib.fs (hunk 3 above)
Comment (OwnageIsMagic) [reply src/Compiler/Utilities/illib.fs:84]: There is another one https://github.com/dotnet/fsharp/pull/16066/files#diff-afc3ed6b692f9f687b04f4f72e14b3d2592245ca7a334476c07c162838d90304R87 , but in FSharp.Core and neither is accessible there https://github.com/dotnet/fsharp/blob/fb39b9440dd27f5ed093e0617cdce49d9dbffa3c/src/Compiler/Utilities/sformat.fs#L1531C48-L1531C60
Any suggestions?

File: src/Compiler/AbstractIL/il.fs [hunk 4]
```diff
@@ -55,10 +55,10 @@ type PrimaryAssembly =
     static member IsPossiblePrimaryAssembly(fileName: string) =
         let name = System.IO.Path.GetFileNameWithoutExtension(fileName)
 
-        String.Compare(name, "mscorlib", true) <> 0
```
Comment (OwnageIsMagic) [inline src/Compiler/AbstractIL/il.fs:58]: I changed `<>` to `=` here. Or I did misunderstand something. This was introduced in https://github.com/dotnet/fsharp/pull/13870

**Comment by OwnageIsMagic** [comment]
@vzarytovskii All tests are passing. I will fix `CheckCodeFormatting` with the next review feedback commit.

File: src/Compiler/FSComp.txt (hunk 1 above)
Comment (vzarytovskii) [reply src/Compiler/FSComp.txt:239]: Yeah, it's better to not trigger it if no change to the message is introduced.

File: src/Compiler/SyntaxTree/XmlDoc.fs (hunk 2 above)
Comment (vzarytovskii) [reply src/Compiler/SyntaxTree/XmlDoc.fs]: Interesting, perhaps there's some special case in parser for it.

https://sharplab.io/#v2:DYLgZgzgNAJiDUAfYBTALgAgB4YLwYHIig==

I didn't know that

File: src/Compiler/Utilities/illib.fs (hunk 3 above)
Comment (vzarytovskii) [reply src/Compiler/Utilities/illib.fs:84]: I think it's fine to leave those. I'm mostly asking why do we use custom one in compiler now instead of BCL one now?

Solely for the purpose of inlining?

Comment (OwnageIsMagic) [reply src/Compiler/Utilities/illib.fs:84]: No, the whole point of this PR is that `Char.IsDigit` (see [impl](https://github.com/dotnet/runtime/blob/c92caa419873bbb5c51997c0f613ea5b5b1d22ec/src/libraries/System.Private.CoreLib/src/System/Char.cs#L317)) is testing for Unicode definition of 'Digit'. So it returns `true` not only for `0-9`, but also for the whole bunch of [other code points](https://www.fileformat.info/info/unicode/category/Nd/list.htm). But the code doesn't account for that i.e. https://github.com/dotnet/fsharp/pull/16066/files#diff-afc3ed6b692f9f687b04f4f72e14b3d2592245ca7a334476c07c162838d90304R160 `'۹' - '0' = 1737`
From performance perspective it's clearly win -- this should compile to only 3 instructions (add,cmp,setb) and eliminates branch, but I assume this will be completely unnoticeable.

Comment (OwnageIsMagic) [reply src/Compiler/Utilities/illib.fs:84]: The other part is switch to char overloads where possible (they are not culture sensitive) and explicitly specify `Ordinal` with string overloads (default is `CurrentCulture`).
\+ bunch of `ToLower` -> `ToLowerInvariant` for deterministic compilation regardless user culture.

Comment (vzarytovskii) [reply src/Compiler/Utilities/illib.fs:84]: I see, you mentioned that it's technically a breaking change, which is technically true. Can you think of any specific examples it may break?

Comment (OwnageIsMagic) [reply src/Compiler/Utilities/illib.fs:84]: Yes, it's presented in OP.
Currently fsc accepting non ascii digits as valid printf width/precession specifiers (both as literal and as `*` arg) and makes non-nonsensical calculations with them. Now it will error out. Most other usages of `Char.IsDigit` are mostly in IL parsing.

[This check](https://github.com/dotnet/fsharp/pull/16066/files#diff-a4284a03583b6abfea98b69073e5409f3fe132a6caf7b2700e6e26ee6430e55cL3248) for example fails for scripts without cases (Hebrew, most Asian langs).
Non invariant ToUpper/Lower with tr_TR and az_AZ locales trashes letter `i` (it doesn't roundtrip).
Culture sensitive path compassion [here](https://github.com/dotnet/fsharp/pull/16066/files#diff-7ab39733da4162be47a5ab74224f8a7b8e7f129e2b67538534f0a0135f02193eL1320) may resolve to different files.

Comment (vzarytovskii) [reply src/Compiler/Utilities/illib.fs]: > Yes, it's presented in OP.
> 
> Currently fsc accepting non ascii digits as valid printf width/precession specifiers (both as literal and as `*` arg) and makes non-nonsensical calculations with them. Now it will error out. Other usages of `Char.IsDigit` are mostly in IL parsing.
> 
> 
> 
> [This check](https://github.com/dotnet/fsharp/pull/16066/files#diff-a4284a03583b6abfea98b69073e5409f3fe132a6caf7b2700e6e26ee6430e55cL3248) for example fails for scripts without cases (Hebrew, most Asian langs).
> 
> Non invariant ToUpper/Lower with tr_TR and az_AZ locales trashes letter `i` (it doesn't roundtrip).
> 
> Culture sensitive path compassion [here](https://github.com/dotnet/fsharp/pull/16066/files#diff-7ab39733da4162be47a5ab74224f8a7b8e7f129e2b67538534f0a0135f02193eL1320) may resolve to different files.

Oh, so most of them are not the most legit use cases. This type of breaking change is ok, I think and we can treat it as a fix.

**Review by T-Gro — APPROVED** [review]

**Comment by psfinaki** [comment]
@OwnageIsMagic I would be happy to review this next week - would you mind resolving the conflicts here? If you need any help with that, please let us know :)

**Comment by OwnageIsMagic** [comment]
@psfinaki Sorry for delay. Most conflicts are from the similar https://github.com/dotnet/fsharp/pull/16439

File: src/Compiler/AbstractIL/il.fs (hunk 4 above)
Comment (OwnageIsMagic) [reply src/Compiler/AbstractIL/il.fs:57]: https://github.com/dotnet/fsharp/blob/b4afa997c703f2ed3e29ab4da1815b0090ecf514/src/Compiler/Driver/CompilerImports.fs#L2437-L2447
based on calling context this bug was resulting in making any framework assembly as primary assembly equivalent, this may affect some esoteric .NET implementations.

File: src/Compiler/Checking/CheckFormatStrings.fs [hunk 5]
```diff
@@ -371,7 +371,7 @@ let parseFormatStringInternal
             // type checker.  They should always have '(...)' after for format string.
             let requireAndSkipInterpolationHoleFormat i =
                 if i < len && fmt[i] = '(' then
-                    let i2 = fmt.IndexOfOrdinal(")", i+1)
+                    let i2 = fmt.IndexOf(')', i+1)
```
Comment (psfinaki) [inline src/Compiler/Checking/CheckFormatStrings.fs:374]: Why not ordinal here?

File: src/Compiler/AbstractIL/ilwrite.fs [hunk 6]
```diff
@@ -3756,7 +3756,7 @@ let writePdb (
                         let pdbfileInfo = FileInfo(pdbfile).FullName
 
                         // If pdbfilepath matches output filepath then error
-                        if String.Compare(outfileInfo, pdbfileInfo, StringComparison.InvariantCulture) = 0 then
+                        if outfileInfo = pdbfileInfo then
```
Comment (psfinaki) [inline src/Compiler/AbstractIL/ilwrite.fs:3759]: What's the particular motivation for this one?

File: src/Compiler/Checking/NicePrint.fs [hunk 7]
```diff
@@ -925,7 +925,7 @@ module PrintTypes =
               if not denv.includeStaticParametersInTypeNames then
                   None, args
               else
-                  let regex = System.Text.RegularExpressions.Regex(@"\`\d+")
+                  let regex = System.Text.RegularExpressions.Regex(@"\`\d+", System.Text.RegularExpressions.RegexOptions.ECMAScript)
```
[the remark this answers is not in the document]
Comment (OwnageIsMagic) [reply src/Compiler/Checking/NicePrint.fs:928]: See notes in OP.
By default `Regex` is Unicode aware, so char classes maps to Unicode categories and allow much more then expected here ASCII chars.

File: src/Compiler/Checking/CheckFormatStrings.fs (hunk 5 above)
Comment (OwnageIsMagic) [reply src/Compiler/Checking/CheckFormatStrings.fs:374]: char overloads are always Ordinal. My PR is larger than https://github.com/dotnet/fsharp/pull/16439 (that introduced `IndexOfOrdinal` ext method) and established usage of char overload.
\+ potentially it's faster on netfx (on Core it delegated to the same Span function)

File: src/Compiler/AbstractIL/ilwrite.fs (hunk 6 above)
Comment (OwnageIsMagic) [reply src/Compiler/AbstractIL/ilwrite.fs:3759]: File systems usually doesn't normalize Unicode in paths, InvariantCulture does

Comment (T-Gro) [reply src/Compiler/AbstractIL/ilwrite.fs:3759]: Those paths are CLI arguments, the logic to compare them should stay case insensitive like it was, to keep the behavior the same.

**Review by T-Gro — CHANGES_REQUESTED** [review]
Ilwrite behavior to comparing CLI args should not be changed.

File: src/Compiler/AbstractIL/ilwrite.fs (hunk 6 above)
Comment (OwnageIsMagic) [reply src/Compiler/AbstractIL/ilwrite.fs:3759]: @T-Gro it was `InvariantCulture`, not `InvariantCultureIgnoreCase`

Comment (OwnageIsMagic) [reply src/Compiler/AbstractIL/ilwrite.fs:3759]: @T-Gro do you suggest to actually make it case insensitive?

File: src/Compiler/Checking/CheckFormatStrings.fs (hunk 5 above)
Comment (OwnageIsMagic) [reply src/Compiler/Checking/CheckFormatStrings.fs:374]: Also there is https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1865-ca1867 and https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1847

**Comment by OwnageIsMagic** [comment]
Any help needed?

File: src/Compiler/Checking/NicePrint.fs (hunk 7 above)
[the remark this answers is not in the document]
Comment (brianrourkeboll) [reply src/Compiler/Checking/NicePrint.fs:928]: Instead of a regular expression, this could also just be something like:

```fsharp
let tryGetTyparCount (s: string) =
    let indexOfBacktick = s.LastIndexOf '`'
    if indexOfBacktick >= 0 && indexOfBacktick < s.Length then
        match Int32.TryParse(s.AsSpan(indexOfBacktick + 1)) with
        | true, genericArgCount -> ValueSome genericArgCount
        | false, _ -> ValueNone
    else
        ValueNone
```

**Comment by OwnageIsMagic** [comment]
@KevinRansom Most fixes in this PR are in 3 categories.

1\. Micro optimizations like using `String.Equals(...)` vs `String.Compare(...) = 0`, using `char` overload instead of `string`, etc.
I agree that this part is mostly irrelevant to this PR, but I was checking all instances of string comparison in code base and it just bothered me. Luckily it's in separate commit, so I can easily drop it.
2. Correctness
There is no way to test this (beside linking with custom Unicode lib).
like
```diff
         member spec.IsGFormat = 
-            spec.IsDecimalFormat || System.Char.ToLower(spec.TypeChar) = 'g'
+            spec.IsDecimalFormat || spec.TypeChar = 'g' || spec.TypeChar = 'G'
```
Currently there is no codepoint in Unicode beside `'G'` that will produce `'g'` after calling `ToLower`, but it doesn't mean we should use Unicode conversion for this.
or
```diff
-          Regex(@"^(/|--)test:ErrorRanges$", RegexOptions.Compiled ||| RegexOptions.IgnoreCase)
+          Regex(
+              @"^(/|--)test:ErrorRanges$",
+              RegexOptions.Compiled
+              ||| RegexOptions.IgnoreCase
+              ||| RegexOptions.CultureInvariant
            )
```
Command line flags are literals and should not be compared with default `CurrentCulture`. But I can't imagine any test input that will uncover bug with current Unicode version.

3\. Actual bugs
Mostly due to assuming `Char.IsDigit` only detects ASCII digits.
```diff
-            while (Char.IsDigit s.[i]) do
+            while (isDigit s[i]) do
                 let n = int s.[i] - int '0'
```
This one manifests itself in `printf`.
Or using Current/Invariant culture for path comparisons.
Most common file systems (I checked NTFS and ext4) do not normalize Unicode:
```powershell
([char]0x2126).ToString().Equals( ([char]0x3a9).ToString(), 'InvariantCulture')
#True

New-Item -Type File ([char]0x2126).ToString()
New-Item -Type File ([char]0x3a9).ToString()

ls
    Directory: D:\tst

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          14.05.2024     0:26              0 Ω
-a---          14.05.2024     0:25              0 Ω
```
It's 2 different files.

----

The only place where Unicode or culture aware comparison should be used is for identifiers in user code.
In all other places only `Ordinal` (and maybe `OrdinalIgnoreCase`) should be used. You need code analyzer, not regression tests.

**Comment by T-Gro** [comment]
I think this is a viable approach.

1. A micro-optimization PR which does not fix nor change anything, only makes it faster

2. Bugfixes with added tests (failing before, success after) - also important to keep them around as regression tests, just in case someone would want to go in the opposite direction several years later.

Formatted printing, CLI argument handling as well as file system ops should be coverable with tests.
