### ISSUE TITLE
Cannot implement interface

### ISSUE THREAD

**Issue by kevmal** [dotnet/fsharp#11015]
This comes from attempting to implement an interface in a commercial assembly which seems to work fine with F# 4.5. I think I've reduced it to the following:

```fsharp
open System 
open System.IO
open System.Reflection
open System.Reflection.Emit

Directory.SetCurrentDirectory __SOURCE_DIRECTORY__

let name = AssemblyName("TestASM")
let assemblyBuilder = AppDomain.CurrentDomain.DefineDynamicAssembly(name, AssemblyBuilderAccess.Save)
let moduleBuilder = assemblyBuilder.DefineDynamicModule("TestASM", "TestASM.dll")
let typeBuilder = 
    let attr = TypeAttributes.Interface ||| TypeAttributes.Public ||| TypeAttributes.AnsiClass ||| TypeAttributes.Abstract 
    moduleBuilder.DefineType("TestASM.MyInterface", attr)
let _methodBuilder = 
    let attr = MethodAttributes.Public ||| MethodAttributes.HideBySig ||| MethodAttributes.Abstract ||| MethodAttributes.Virtual
    typeBuilder.DefineMethod("MyMethod", attr)
typeBuilder.CreateType()
assemblyBuilder.Save("TestASM.dll")

#r "TestASM.dll"

{new TestASM.MyInterface with 
    member x.MyMethod() = ()
}
```

This works with F# 4.5 but not F# 4.7 or F# 5.0.

Error is 
```
error FS0767: The member 'MyMethod' does not correspond to any abstract or virtual method available to override or implement.
```

**Comment by TIHan** [comment]
I have a fix. One temp workaround is adding `MethodAttributes.NewSlot` to the method attributes.

**Comment by cartermp** [comment]
fixed in https://github.com/dotnet/fsharp/pull/11426#issuecomment-824295127
