### PR TITLE
Fix for #11610 + bump SDK to 5.0.300

### LINKED ISSUE #11610: Regression on SDK 5.0.300: When using an identifier like __SOURCE_DIRECTORY__ in a type parameter one get FS3045 compilation error.
Please provide a succinct description of the issue.

When using SDK 5.0.300 and one uses an identifier in a type parameter one get a FS3045 compilation error.
It works on SDK 5.0.203

Provide the steps required to reproduce the problem:

1. Use SDK 5.0.300
2. Compile the code below, also see [FS3045 error reproduction repro](https://github.com/da9l/repro50300sdkFS3045Error)

```fsharp
open System
open FSharp.Data

type Sample = XmlProvider<Schema="Sample.xsd",
                          ResolutionFolder=__SOURCE_DIRECTORY__>

```

**Expected behavior**

It should work as it does in SDK 5.0.203.

**Actual behavior**

A FS3045 compilation error.

**Known workarounds**

1. Use SDK 5.0.203
2. Put the identifier into a `[<Literal>]` value.

```fsharp
[<Literal>]
let refDir = __SOURCE_DIRECTORY__
type Sample = XmlProvider<Schema="Sample.xsd",
                          ResolutionFolder=refDir>
```

Provide any related information (optional):

* Operating system: Windows 10
* .NET Runtime kind (.NET Core, .NET Framework, Mono): dotnet-sdk 5.0.300
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Visual Studio Code (probably not related)

### PR DESCRIPTION
**Pull request by vzarytovskii**
Bump SDK to 5.0.300 (+corresponding runtime), fixes #11610, adds test to check that `SynConst.SourceIdentifier` is recognized as valid static argument to a provided type.

### CODE REVIEW

**Comment by cartermp** [comment]
Does this also address having `#I __SOURCE_DIRECTORY__` at the top of a script?

**Comment by vzarytovskii** [comment]
> Does this also address having `#I __SOURCE_DIRECTORY__` at the top of a script?

I'm not sure that's the same issue, this one only fixes the source identifiers as static arguments.

**Review by brettfo — APPROVED** [review]
