### ISSUE TITLE
Compile errors while using PInvoke with Delegates

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#7744]
I can't represent some PInvoke constructs in F# after translating them from C#, specifically related to Unmanaged Function Pointers and F# Delegate declarations.

**Repro steps**

Given the following C# code:
```csharp
using System;
using System.Runtime.InteropServices;       

namespace Sample {
  [UnmanagedFunctionPointer(CallingConvention.StdCall)]
  public delegate void YR_COMPILER_CALLBACK_FUNC(int error_level, [In, MarshalAs(UnmanagedType.LPStr)] string file_name, int line_number, [In()] [MarshalAs(UnmanagedType.LPStr)] string message, IntPtr user_data);
}
```

Translate it into the following F#:
```fsharp

module Sample

open System
open System.Runtime.InteropServices

[<UnmanagedFunctionPointer(CallingConvention.StdCall)>]
type YR_COMPILER_CALLBACK_FUNC = delegate of int * [<In; MarshalAs(UnmanagedType.LPStr)>] string * int * [<In; MarshalAs(UnmanagedType.LPStr)>] string * IntPtr -> unit;
```

**Expected behavior**

The delegate type can be defined, and instances of it can be created.

**Actual behavior**

The following compiler errors are generated:
* `This attribute is not valid for use on this language element F# Compiler(842)`
  * This is on the `UnmanagedFunctionPointer` usage on the `type YR_COMPILER_CALLBACK_FUNC` declaration
* `Augmentations are not permitted on delegate type moduleDefns F# Compiler(545)`
  * This is on the entire `delegate of...` definition.

**Known workarounds**

Define the callback in C# and consume/use it from F#.

**Related information**

Provide any related information (optional):

* Operating system: MacOS
* .Net Core
* FCS 32 (~October 2019)

It seems that the [delegate handling](https://github.com/dotnet/fsharp/blob/master/src/fsharp/pars.fsy#L1517-L1525) disallows augmentations on delegate members, but I don't understand what part of my declaration is an augmentation.

**Comment by cartermp** [comment]
I think this should probably be supported.

**Comment by baronfel** [comment]
An oddity is that the UnmanagedFunctionPointer attribute has AttributeUsage.Delegate, implying that the compiler doesn't understand or interpret that type declaration correctly when evaluating attribute use

**Comment by FunctionalFirst** [comment]
FWIW, the following works fine on Win10, FSI 10.6 for F# 4.7—
```f#
open System
open System.Runtime.InteropServices

[<UnmanagedFunctionPointer(CallingConvention.StdCall)>]
type YR_COMPILER_CALLBACK_FUNC = 
    delegate of 
        errorLevel: int * 
        [<In; MarshalAs(UnmanagedType.LPStr)>] fileName: string * 
        lineNumber: int * 
        [<In; MarshalAs(UnmanagedType.LPStr)>] ruleName: string * 
        userData: IntPtr -> unit
```
However, before adding parameter names I got this error:
> error FS0640: A parameter with attributes must also be given a name, e.g. '[<Attribute>] Name : Type'

**Comment by baronfel** [comment]
Odd, that works for me as well.

Code without parameter names fails with the error you describe, code with parameter names compiles as you describe. Currently trying to compile the same script with FSC directly to see what the result is.

**Comment by baronfel** [comment]
I can't explain this anymore, it now works in the library file I had been using for this effort.
