### ISSUE TITLE
error FS0192: internal error: Error in pass3 for some F# code.

### ISSUE THREAD

**Issue by sylvainouel** [dotnet/fsharp#18066]
**Repro steps**

Copy/paste the following program in F# interactive:

```
type A = {
    F: uint64  
}

type B = {
    C: uint64[]
}

let g x =
    let c = 
        [|
            for d in x.C do
                {
                    F = d
                }
        |]
    c
```

It produces the following error:

error FS0192: internal error: Error in pass3 for type FSI_0003, error: ldelem

**Expected behavior**

I think it should build fine.

**Actual behavior**

internal error

**Known workarounds**
changing the uint64 to int64 fixes it.

**Related information**

It used to work, it stopped working after upgrading to latest VS.

* Operating system
Windows 11

* .NET Runtime kind (.NET Core, .NET Framework, Mono)

.NET 9

* Editing Tools (e.g. Visual Studio Version, Visual Studio)
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.12.1

**Comment by brianrourkeboll** [comment]
Here's a more minimal repro:

```fsharp
[|for x in [|1UL|] -> x|]
```

The same thing applies for `unativeint`:

```fsharp
[|for x in [|1un|] -> x|]
```

The problem seems likely to be here

https://github.com/dotnet/fsharp/blob/95fe045af5b105c27ac401cc99a396c755031ae7/src/Compiler/Optimize/LowerComputedCollections.fs#L393-L394

and here

https://github.com/dotnet/fsharp/blob/95fe045af5b105c27ac401cc99a396c755031ae7/src/Compiler/Optimize/LowerComputedCollections.fs#L360-L374

I think we need to be emitting `ldelem.i8` and `ldelem.i` for `uint64` and `unativeint`, respectively. (And maybe likewise for `stelem`?)

> Even though the previous version was already optimized to Array.map

That was an intermediate optimization introduced in #16948, but superseded in #17067 in part to fix debug stepping in the loop body. SharpLab still has a preview version of 9 that doesn't include #17067, #17419, #17711.

**Comment by brianrourkeboll** [comment]
> **Known workarounds**
> changing the uint64 to int64 fixes it.

@sylvainouel Another workaround for the time being would be to set `<LangVersion>8.0</LangVersion>` in your project file.

**Comment by brianrourkeboll** [comment]
I opened a PR that I believe should fix this: #18081.

**Comment by sylvainouel** [comment]
Thank you for this fix!
