### PR TITLE
Add Oxpecker repository to build check

### PR DESCRIPTION
**Pull request by Lanayx**
## Description

Added Oxpecker repository to build check to prevent issues like https://github.com/dotnet/fsharp/issues/20059

### CODE REVIEW

**Comment by Lanayx** [comment]
CI fails at `Oxpecker.slnx` with 
```
D:\a\_work\1\TestRepo\src\Oxpecker.ViewEngine\Render.fs(61,17): error FS0001: The type 'IAsyncDisposable' is not compatible with the type 'IDisposable' [D:\a\_work\1\TestRepo\src\Oxpecker.ViewEngine\Oxpecker.ViewEngine.fsproj]
D:\a\_work\1\TestRepo\src\Oxpecker.ViewEngine\Render.fs(61,13): error FS0001: The type 'IAsyncDisposable' is not compatible with the type 'IDisposable' [D:\a\_work\1\TestRepo\src\Oxpecker.ViewEngine\Oxpecker.ViewEngine.fsproj]
D:\a\_work\1\TestRepo\src\Oxpecker.ViewEngine\Render.fs(76,17): error FS0001: The type 'IAsyncDisposable' is not compatible with the type 'IDisposable' [D:\a\_work\1\TestRepo\src\Oxpecker.ViewEngine\Oxpecker.ViewEngine.fsproj]
D:\a\_work\1\TestRepo\src\Oxpecker.ViewEngine\Render.fs(76,13): error FS0001: The type 'IAsyncDisposable' is not compatible with the type 'IDisposable' [D:\a\_work\1\TestRepo\src\Oxpecker.ViewEngine\Oxpecker.ViewEngine.fsproj]
```
I've no idea why, locally it builds fine with 10.0.100 or later

**Comment by majocha** [comment]
> Encountered conflict between 'Reference:D:\a\_work\1/FSharpCompiler/artifacts/bin/FSharp.Core/Release/netstandard2.0/FSharp.Core.dll' and 'Reference:C:\Users\cloudtest\.nuget\packages\fsharp.core\10.0.100\lib\netstandard2.1\FSharp.Core.dll'. Choosing 'Reference:D:\a\_work\1/FSharpCompiler/artifacts/bin/FSharp.Core/Release/netstandard2.0/FSharp.Core.dll' because AssemblyVersion '11.0.0.0' is greater than '10.0.0.0'.

It loads ns20 FSharp.Core which has no IAD support.

**Comment by Lanayx** [comment]
> It loads ns20 FSharp.Core which has no IAD support.

This doesn't make sense, all Oxpecker projects target .NET 10, so ns21 should be chosen, not ns20.

**Comment by majocha** [comment]
I think it's the shims to use local compiler in the CI, they probably add the reference to ns20 library. That msbuild prefers it is another story.

**Comment by T-Gro** [comment]
@copilot resolve the merge conflicts in this pull request

**Comment by T-Gro** [comment]
Oxpecker added with https://github.com/dotnet/fsharp/pull/20240

**Comment by Lanayx** [comment]
@T-Gro This PR tried to add both Oxpecker solutions, but #20240 adds only one of them, should I create a new PR to add the second one?
