### PR TITLE
Fix broken unit test

### LINKED ISSUE #12348: Build failed
The compiler is failing to build

**Repro steps**

```sh
git clone https://github.com/dotnet/fsharp.git
```

```sh
PS C:\Users\wesle\source\repos\fsharp> .\Build.cmd
Build FAILED.

C:\Users\wesle\source\repos\fsharp\tests\service\TreeVisitorTests.fs(60,14): error FS0727: This union case expects 7 ar
guments in tupled form [C:\Users\wesle\source\repos\fsharp\tests\FSharp.Compiler.UnitTests\FSharp.Compiler.UnitTests.fs
proj]
C:\Users\wesle\source\repos\fsharp\tests\service\TreeVisitorTests.fs(60,48): error FS0727: This union case expects 7 ar
guments in tupled form [C:\Users\wesle\source\repos\fsharp\tests\FSharp.Compiler.UnitTests\FSharp.Compiler.UnitTests.fs
proj]
C:\Users\wesle\source\repos\fsharp\tests\service\TreeVisitorTests.fs(60,14): error FS0727: This union case expects 7 ar
guments in tupled form [C:\Users\wesle\source\repos\fsharp\tests\FSharp.Compiler.UnitTests\FSharp.Compiler.UnitTests.fs
proj]
C:\Users\wesle\source\repos\fsharp\tests\service\TreeVisitorTests.fs(60,48): error FS0727: This union case expects 7 ar
guments in tupled form [C:\Users\wesle\source\repos\fsharp\tests\FSharp.Compiler.UnitTests\FSharp.Compiler.UnitTests.fs
proj]
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:05:07.81
Build failed with exit code 1. Check errors above.
```

### PR DESCRIPTION
**Pull request by omppye**
The codebase is failing to build
The build error was introduced in #11641

This PR fix it and also closes #12348

### CODE REVIEW

**Review by vzarytovskii — APPROVED** [review]
Thanks for the fix. I will need to look at the pr which introduced it and understand why did it pass CI.

**Comment by kerams** [comment]
@vzarytovskii, I'm guessing because `SynEnumCase` changed in main after main was merged into the PR branch.

**Comment by vzarytovskii** [comment]
> @vzarytovskii, I'm guessing because `SynEnumCase` changed in main after main had been merged into the PR branch.

Yeah, that was my guess, didn't look at it yet. We probably need to pay closer attention to the after-merge CI status.
