### ISSUE TITLE
Regression on SDK 5.0.300: When using an identifier like __SOURCE_DIRECTORY__ in a type parameter one get FS3045 compilation error.

### ISSUE THREAD

**Issue by da9l** [dotnet/fsharp#11610]
Please provide a succinct description of the issue.

When using SDK 5.0.300 and one uses an identifier in a type parameter one get a FS3045 compilation error.
It works on SDK 5.0.203

Provide the steps required to reproduce the problem:

1. Use SDK 5.0.300
2. Compile the code below, also see [FS3045 error reproduction repro](https://github.com/da9l/repro50300sdkFS3045Error)

```fsharp
open System
open FSharp.Data

type Sample = XmlProvider<Schema="Sample.xsd",
                          ResolutionFolder=__SOURCE_DIRECTORY__>

```

**Expected behavior**

It should work as it does in SDK 5.0.203.

**Actual behavior**

A FS3045 compilation error.

**Known workarounds**

1. Use SDK 5.0.203
2. Put the identifier into a `[<Literal>]` value.

```fsharp
[<Literal>]
let refDir = __SOURCE_DIRECTORY__
type Sample = XmlProvider<Schema="Sample.xsd",
                          ResolutionFolder=refDir>
```

Provide any related information (optional):

* Operating system: Windows 10
* .NET Runtime kind (.NET Core, .NET Framework, Mono): dotnet-sdk 5.0.300
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Visual Studio Code (probably not related)

**Comment by nbevans** [comment]
Seeing something similar in a .fsx

![image](https://user-images.githubusercontent.com/542188/119956935-82c85280-bf99-11eb-8679-086cd158540b.png)

**Comment by cartermp** [comment]
Self-assigning myself to triage and determine if there was a regression when the holiday is over.

**Comment by cartermp** [comment]
Confirmed regression, this breaks numerous scripts

**Comment by cartermp** [comment]
Tagging @vzarytovskii, we use `__SOURCE_DIRECTORY__` quite heavily in our test scripts, and in our .NET 6 build of the repo these don't fail. So we'll want to determine if this is actually us, or if there was some regression that slipped into the most recent .NET SDK.

**Comment by vzarytovskii** [comment]
Interestingly, enough, it seems to be not working in the given type provider, but works fine in, for example, attributes.

**Comment by vzarytovskii** [comment]
Ok, I think I know how to fix it. Gonna have the PR soon.

**Comment by CaptnCodr** [comment]
When is this fix available?

**Comment by vzarytovskii** [comment]
@CaptnCodr i think we merged it after 5.0.301 was preparing for release, unfortunately :(
@cartermp do you know if the change gonna be in with next patch? I think we got it into 16.11.

**Comment by cartermp** [comment]
Should be in the next month, so long as the SDK also releases around then.

**Comment by cartermp** [comment]
Note that our insertions for dev17 aren't working yet, so we're quite a bit behind. And there's no autoamtic insertions into 16.11, so we need to service the fix.

**Comment by Swoorup** [comment]
Looks like isn't fixed for 5.0.302 as well?

**Comment by vzarytovskii** [comment]
> Looks like isn't fixed for 5.0.302 as well?

Good question. I'm not entirely sure what went into 302. @KevinRansom @brettfo what's the easiest way to tell what commit 302 is?

**Comment by nhirschey** [comment]
This is still broken in 5.0.400.

![dotnet5 0 400](https://user-images.githubusercontent.com/5226115/129363734-ee75a035-1eb0-4d88-bf12-d2129905fa28.gif)


```fsharp
#r "nuget: FSharp.Data,4.2.2"

open FSharp.Data

let lines = ["A,B";"1,2"]
System.IO.File.WriteAllLines("test.csv", lines)

// Does not work
type Test = CsvProvider<__SOURCE_DIRECTORY__ + "/test.csv",ResolutionFolder= __SOURCE_DIRECTORY__>
Test.GetSample()

// This works
let [<Literal>] SourceDir = __SOURCE_DIRECTORY__
type Test2 = CsvProvider<"test.csv",ResolutionFolder= SourceDir>
Test2.GetSample()
```

**Comment by dsyme** [comment]
@nhirschey Yes it looks like the fix isn't in the release branch for 16.11, which is a shame

https://github.com/dotnet/fsharp/commits/release/dev16.11

We're after this commit: https://github.com/dotnet/fsharp/commit/78826fdd4d5918eb4d42bf8f2799b7347d2aa60c

The fix will certainly be in .NET 6.0
