### ISSUE TITLE
FS0073: internal error: ImportILTypeRef: unexpected local scope using System.Collections.Immutable

### ISSUE THREAD

**Issue by marklam** [dotnet/fsharp#16321]
Calling `ImmutableQueue.Dequeue` or `IImmutableStack.Pop` causes internal compiler errors

**Repro steps**

1. Clone https://github.com/fsprojects/FSharp.Collections.Immutable
2. dotnet build

**Expected behavior**

Compilation succeeds

**Actual behavior**

```text
FSharp.Collections.Immutable\src\FSharp.Collections.Immutable\stack.fs(33,9): error FS0073: internal error: ImportILTypeRef: unexpected local scope
FSharp.Collections.Immutable\src\FSharp.Collections.Immutable\stack.fs(42,33): error FS0073: internal error: ImportILTypeRef: unexpected local scope
FSharp.Collections.Immutable\src\FSharp.Collections.Immutable\queue.fs(28,47): error FS0073: internal error: ImportILTypeRef: unexpected local scope
```

**Known workarounds**

As per @vzarytovskii 's [comment below](https://github.com/dotnet/fsharp/issues/16321#issuecomment-1821454236), Adding `<LangVersion>7.0</LangVersion>` to a `PropertyGroup` in the fsproj allows the compilation to succeed.

**Related information**

* Operating system : Windows 10
```text
c:\git>dotnet --list-sdks
6.0.417 [C:\Program Files\dotnet\sdk]
8.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by vzarytovskii** [comment]
builds with `7.0.404`, so something recent

**Comment by vzarytovskii** [comment]
Also builds with `<LangVersion>7.0</LangVersion>`, so, something from `8.0` featureset.

**Comment by marklam** [comment]
@vzarytovskii: Edited the issue to add that workaround, thanks.

**Comment by auduchinok** [comment]
This may have also been fixed by #16390.

**Comment by KevinRansom** [comment]
This is fixed in the shipped SDK 8.0.200.

![image](https://github.com/dotnet/fsharp/assets/5175830/fae12589-d42d-4a48-9b80-5742a1360be5)
