### ISSUE TITLE
Cannot launch F# interactive after upgrading to 16.9

### ISSUE THREAD

**Issue by zyzhu** [dotnet/fsharp#11191]
Please provide a succinct description of the issue.

After installing VS 2019 16.9. Launching FSI shows error message.

Provide the steps required to reproduce the problem:

1. Open Visual Studio 2019 16.9. Launch F# interactive window. The error message shows up and the session is terminated. If I press enter, the error message will show up again.
2. I also tried to run fsianycpu from the installation location. I got the same error message
3. If I switch to "Use .Net Core Scripting", the new FSI works just fine. But I prefer the old one as the new one does not seem to support script debugging yet.

**Expected behavior**

FSI shall work just fine.

**Actual behavior**

The error message
```
error FS0193: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).

Exception by fsi.exe:
System.Exception: Error creating evaluation session: System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Utilities.Traits.get_Instance()
   at Microsoft.Build.Tasks.ResolveAssemblyReference.LogInputs()
   at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetRegistrySubKeyNames getRegistrySubKeyNames, GetRegistrySubKeyDefaultValue getRegistrySubKeyDefaultValue, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, OpenBaseKey openBaseKey, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)
   at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()
   at FSharp.Compiler.LegacyMSBuildReferenceResolver.ResolveCore$cont@244(String targetProcessorArchitecture, String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, LegacyResolutionEnvironment resolutionEnvironment, Tuple`2[] references, FSharpFunc`2 logMessage, FSharpFunc`2 logDiagnostic, String implicitIncludeDir, String fsharpCoreDir, FSharpList`1 explicitIncludeDirs, Boolean allowRawFileName, Unit unitVar) in F:\workspace\_work\1\s\src\fsharp\LegacyMSBuildReferenceResolver.fs:line 329
   at FSharp.Compiler.LegacyMSBuildReferenceResolver.getResolver@346.FSharp.Compiler.ILegacyReferenceResolver.Resolve(LegacyResolutionEnvironment resolutionEnvironment, Tuple`2[] references, String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, String targetProcessorArchitecture, String fsharpCoreDir, FSharpList`1 explicitIncludeDirs, String implicitIncludeDir, FSharpFunc`2 logMessage, FSharpFunc`2 logDiagnostic) in F:\workspace\_work\1\s\src\fsharp\LegacyMSBuildReferenceResolver.fs:line 381
   at FSharp.Compiler.CompilerImports.TcConfig.MsBuildResolve(TcConfig tcConfig, Tuple`2[] references, ResolveAssemblyReferenceMode mode, Range errorAndWarningRange, Boolean showMessages) in F:\workspace\_work\1\s\src\fsharp\CompilerImports.fs:line 387
   at FSharp.Compiler.CompilerImports.GetAllDllReferences@536.GenerateNext(IEnumerable`1& next) in F:\workspace\_work\1\s\src\fsharp\CompilerImports.fs:line 554
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 368
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 546
   at FSharp.Compiler.CompilerImports.TcAssemblyResolutions.SplitNonFoundationalResolutions(CompilationThreadToken ctok, TcConfig tcConfig) in F:\workspace\_work\1\s\src\fsharp\CompilerImports.fs:line 566
   at <StartupCode$FSharp-Compiler-Private>.$IncrementalBuild.Get@550.Invoke(Unit unitVar) in F:\workspace\_work\1\s\src\fsharp\service\IncrementalBuild.fs:line 550
   at FSharp.Compiler.AbstractIL.Internal.Library.Cancellable.delay@751.Invoke(CancellationToken ct) in F:\workspace\_work\1\s\src\fsharp\absil\illib.fs:line 751
   at FSharp.Compiler.AbstractIL.Internal.Library.Cancellable.runWithoutCancellation[a](Cancellable`1 comp) in F:\workspace\_work\1\s\src\fsharp\absil\illib.fs:line 756
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2852
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2854
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible, FSharpOption`1 legacyReferenceResolver) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 3180
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Sample.FSharp.Compiler.Interactive.Main.evaluateSession(String[] argv) in F:\workspace\_work\1\s\src\fsharp\fsi\fsimain.fs:line 269
```
**Known workarounds**

I tried to uninstall and reinstall it. But the problem stays. However, on another company desktop, there is no such problem. I do not know what's possible to lead to this situation.

**Related information**

Provide any related information (optional):

* Operating system: Windows 10
* .NET Runtime kind (.NET Core, .NET Framework, Mono): 
I have the following dotnet sdk listed
3.1.202 [C:\Program Files\dotnet\sdk]
3.1.406 [C:\Program Files\dotnet\sdk]
5.0.101 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
5.0.200 [C:\Program Files\dotnet\sdk]
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Visual Studio 2019 Enterprise 16.9

**Comment by zyzhu** [comment]
Asked IT to reinstall it with admin right instead of using the cumbersome software center. Problem is gone. Life without admin right is hard...
