### ISSUE TITLE
FSI: Regression in processing signature files via `load` directive

### ISSUE THREAD

**Issue by pblasucci** [dotnet/fsharp#14032]
It used to be possible to load signature files into an interactive session, via the `#load "path/to/file.fsi"` directive. Currently, this generates an error about missing a corresponding implementation file.

**Repro steps**

1. Create an F# project.
2. Add both a signature file and its corresponding implementation file.
3. Add a script file containing two `#load` directives (one for the signature file and one for the implementation file).
4. Select both load directives and send (together) to an interactive session.

An appropriately set up gist is available here: https://gist.github.com/pblasucci/7c864a98b61cad9190ae84903e99e546 (note: at the time the gist was authored, ~6 months ago, things worked as expected).

**Expected behavior**

Both the signature and implementation file are loaded into the interactive session. No error is generated, and the signature is used to inform evaluation of the implementation file. 

**Actual behavior**

> error FS0240: The signature file 'FSI_0002_Library' does not have a corresponding implementation file. If an implementation file exists then check the 'module' and 'namespace' declarations in the signature and implementation files match.

**Known workarounds**

+ Don't load the signature file into the interactive session. :frowning_face: 
+ Load the compiled assembly into FSI (instead of the sources).

**Related information**

Provide any related information (optional):

* Linux (Pop!_OS 22.04 LTS, 64-bit) _and_ Windows 10 Enterprise (19044.2006, 64-bit)
* .NET 6 (Linux: v6.0.109, Windows: 6.0.203)
* Jet Brain's Rider (Linux: 2022.3 EAP 1, Windows: 2022.2.3)
* Visual Studio Code with Ionide (Linux: 1.67.2 with 7.2.2)

**Comment by vzarytovskii** [comment]
@pblasucci Do you recall which version of SDK was it working on before? I have tested it on 5.0.408, and it's still the same diagnostic.

**Comment by pblasucci** [comment]
Unfortunately, I don't recall exactly. I thought it was .NET 5 -- but it may have been .NET Core 3.x 🫤

**Comment by abonie** [comment]
You can do it in one `#load` directive
```fsharp
#load "Library.fsi" "Library.fs"
```
I think that fully solves the issue?

**Comment by pblasucci** [comment]
Oh my days!!! :scream: 

Thanks, @abonie! That does, indeed, solve the problem. :tada: 

TIL :+1: :smile:
