### ISSUE TITLE
.net core fsi not working with FSharp.Data's JsonProvider, GtkSharp or Qml.Net

### ISSUE THREAD

**Issue by FsharperOnTheRun** [dotnet/fsharp#6688]
Reposting [from reddit](https://www.reddit.com/r/fsharp/comments/bkljpa/net_core_fsi_not_working_with_fsharpdatas/)

I'm trying to use FSharp.Data, GtkSharp and Qml.Net on fsi(dotnet fsi) but its not working. It's not finding assemblies correctly. Maybe i'm doing something wrong.

Using mono(5.20.1.19) + fsharpi (compiled from github fsharp) works. Unfortunately only F# 4.5 is supported.

#### Repro steps

System: Ubuntu 18.10

    dotnet --list-sdks

>2.2.105 \[/home/me/.dotnet/sdk\]  
>  
>2.2.203 \[/home/me/.dotnet/sdk\]  
>  
>3.0.100-preview3-010431 \[/home/me/.dotnet/sdk\]  
>  
>3.0.100-preview4-011223 \[/home/me/.dotnet/sdk\]

I created 2 folders to test using 2 versions of .net core sdk. In each, I set the sdk version to be used then i create the projects.

    dotnet new globaljson --sdk-version 2.2.203 
    dotnet new globaljson --sdk-version 3.0.100-preview4-011223

Create JsonProvider test with

    dotnet new console -lang F# -o test-json 
    cd test-json 
    dotnet add package FSharp.Data 

edit Program.fs:

    module Program
    open System
    open FSharp.Data
    
    type Simple = JsonProvider<""" { "name":"John", "age":94 } """>
    
    let test () = 
        let simple = Simple.Parse(""" { "name":"Tomas", "age":4 } """)
        printfn ".Name: %s; .Age: %i" simple.Name simple.Age
    
    [<EntryPoint>]
    let main argv =
        printfn "Hello World from F#!"
        test()
        0

Build and run works on both(2.2.203 and 3.0.100-preview4-011223):

    dotnet run

>Hello World from F#! .Name: Tomas; .Age: 4

Trying to run on F# interactive (F# 4.6)

    dotnet fsi

On .net core sdk 2.2.203, it can't find System.IO.StringReader

    #r "/home/me/.nuget/packages/fsharp.data/3.1.1/lib/netstandard2.0/FSharp.Data.dll" ;;

>\--> Referenced '/home/me/.nuget/packages/fsharp.data/3.1.1/lib/netstandard2.0/FSharp.Data.dll' (file may be locked by F# Interactive process)

    #load "Program.fs" ;; 

>/home/me/Test/with-sdk-2.2/test-json/Program.fs(9,18): error FS3033: The type provider 'ProviderImplementation.JsonProvider' reported an error in the context of provided type 'FSharp.Data.JsonProvider,Sample=" { "name":"John", "age":94 } "', member 'Parse'. The error: The design-time type 'System.IO.StringReader' utilized by a type provider was not found in the target reference assembly set '\[tgt assembly System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; tgt assembly FSharp.Core, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; tgt assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;  
>  
>\[...\] tgt assembly System.IO, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; tgt assembly System.Reflection, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; tgt assembly System.Reflection.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a;  
>  
>\[...\]

On .net core sdk 3.0.100-preview4-011223, it can't find mscorlib(wtf?)

    #r "/home/me/.nuget/packages/fsharp.data/3.1.1/lib/netstandard2.0/FSharp.Data.dll" ;;

>\--> Referenced '/home/me/.nuget/packages/fsharp.data/3.1.1/lib/netstandard2.0/FSharp.Data.dll' (file may be locked by F# Interactive process)

    #load "Program.fs" ;; 

>/home/me/Test/with-sdk-3-p4/test-json/Program.fs(9,18): error FS3033: The type provider 'ProviderImplementation.JsonProvider' reported an error in the context of provided type 'FSharp.Data.JsonProvider,Sample=" { "name":"John", "age":94 } "', member 'Parse'. The error: assembly mscorlib not found

&#x200B;

For the gtksharp,

    dotnet new console -lang F# -o test-gtk 
    cd test-gtk 
    dotnet add package GtkSharp 

edit Program.fs

    module Program 
    open System 
    open Gtk
    [<EntryPoint>]
    let main argv =
        printfn "Hello World from F#!"
    
        Application.Init()
    
        let App = new Application("org.Samples.Samples", GLib.ApplicationFlags.None)
        App.Register(GLib.Cancellable.Current)
        let Win = new Window(WindowType.Toplevel)
        App.AddWindow(Win)
    
        Win.ShowAll()
        Application.Run()
        0

Build and run works fine

Trying on fsi

    #r "/home/me/.nuget/packages/gtksharp/3.22.24.37/lib/netstandard2.0/GtkSharp.dll" ;; 
    #r "/home/me/.nuget/packages/giosharp/3.22.24.37/lib/netstandard2.0/GioSharp.dll" ;; 
    #r "/home/me/.nuget/packages/glibsharp/3.22.24.37/lib/netstandard2.0/GLibSharp.dll" ;; 
    #r "/home/me/.nuget/packages/atksharp/3.22.24.37/lib/netstandard2.0/AtkSharp.dll" ;; 
    #r "/home/me/.nuget/packages/gdksharp/3.22.24.37/lib/netstandard2.0/GdkSharp.dll" ;; 
    #r "/home/me/.nuget/packages/cairosharp/3.22.24.37/lib/netstandard2.0/CairoSharp.dll" ;;
    #load "Program.fs";;

On .net core sdk 2.2.203:

>error FS3216: type 'Gtk.Application' not found in assembly 'GtkSharp, Version=3.22.24.37, Culture=neutral, PublicKeyToken=null'. A possible cause may be a version incompatibility. You may need to explicitly reference the correct version of this assembly to allow all referenced components to use the correct version.

On .net core sdk 3.0.100-preview4-011223, same error:

>error FS3216: type 'Gtk.Application' not found in assembly 'GtkSharp, Version=3.22.24.37, Culture=neutral, PublicKeyToken=null'. A possible cause may be a version incompatibility. You may need to explicitly reference the correct version of this assembly to allow all referenced components to use the correct version.

&#x200B;

For the Qml.net,

    dotnet new console -lang F# -o test-qml 
    cd test-qml 
    dotnet add package Qml.Net 
    dotnet add package Qml.Net.LinuxBinaries 

edit Program.fs

    module Program
    open System
    open System.IO
    
    open Qml.Net
    open Qml.Net.Runtimes
    
    [<EntryPoint>]
    let main argv =
        printfn "Hello World from F#!"
    
        RuntimeManager.DiscoverOrDownloadSuitableQtRuntime()
    
        use application = new QGuiApplication()
        use qmlEngine = new QQmlApplicationEngine()
        qmlEngine.Load("Main.qml")
    
        application.Exec()

Build and run works fine as well

Trying on Fsi with:

    #r "/home/me/.nuget/packages/qml.net/0.10.1/lib/netstandard2.0/Qml.Net.dll" ;; 
    #load "Program.fs" ;; 
    Program.main[||];;

On .net core sdk 2.2.203:

>Hello World from F#! System.IO.FileNotFoundException: Could not load file or assembly 'NetNativeLibLoader, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.  
>  
>File name: 'NetNativeLibLoader, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null' at Qml.Net.Runtimes.RuntimeManager.ConfigureRuntimeDirectory(String directory) at Qml.Net.Runtimes.RuntimeManager.DiscoverOrDownloadSuitableQtRuntime(RuntimeSearchLocation runtimeSearchLocation) at FSI\_0002.Program.main(String\[\] argv) at <StartupCode$FSI\_0003>.$FSI\_0003.main@()

Adding a reference to the NetNativeLibLoader as well does not change the error.

    #r "/home/me/.nuget/packages/netnativelibloader/0.1.1/lib/netstandard2.0/NetNativeLibLoader.dll" ;;

On .net core sdk 3.0.100-preview4-011223

>...Same error as in 2.2.203...

#### Expected behavior

Loading the correct dependencies

#### Actual behavior

Fails to load many dependencies

#### Known workarounds

Only jsonprovider test managed to work if I reference the libraries in the command line using -r:full-path to each. 

#### Related information 

* Ubuntu 18.10
* installed via dotnet-install.sh

**Comment by cartermp** [comment]
I'm not sure what the root issue here, but my inclination is that we wait until #5850 is completed before looking at how third-party dependencies are pulled in.

**Comment by cartermp** [comment]
This is now completed with `#r: "nuget:..."`. To use it from FSI, you can do this: `dotnet fsi /langversion:preview`.
