### PR TITLE
fix 10734

### LINKED ISSUE #10734: F# 5.0 regression, FS5 sample project no longer builds.  CE's broken.
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/F-50-regression-FS5-sample-project-no/1286065)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.8.3]
Visual Studio 16.9.0 Preview 2 can no longer build the fs5sample project (https://github.com/cartermp/fs5-samples.git) as custom keywords in computation expressions (CE's) no longer seem to support optional parameters.

Intellisense is also showing the errors.

But the project will build successfully from the command line (dotnet build), using the installed .net 5.0.200-preview.20601.7

And the same project will also edit and build ok using Visual Studio 16.8.3

---
#### Feedback Bot on 12/13/2020, 09:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by dsyme**
Fixes #10734 - a simple fix to not fix an argument count in the cases where optional or ParamArray arguments are used

### CODE REVIEW

**Review by TIHan — APPROVED** [review]

**Review by cartermp — APPROVED** [review]

**Comment by KevinRansom** [comment]
Test failure: Pretty sure it's related.
````

 line 189
  - neg60.fs(186,9,186,24): typecheck error FS3099: 'with_validators' is used with an incorrect number of arguments. This is a custom operation in this query or computation expression. Expected 1 argument(s), but given 2.
  + neg60.fs(178,9,178,24): typecheck error FS3099: 'with_validators' is used with an incorrect number of arguments. This is a custom operation in this query or computation expression. Expected 0 argument(s), but given 1.
 diff between [D:\workspace\_work\1\s\tests\fsharp\typecheck\sigs\neg60.bsl] and [D:\workspace\_work\1\s\tests\fsharp\typecheck\sigs\neg60.err]
 line 191
  - neg60.fs(195,9,195,24): typecheck error FS3099: 'with_validators' is used with an incorrect number of arguments. This is a custom operation in this query or computation expression. Expected 1 argument(s), but given 3.
  + neg60.fs(185,9,185,13): typecheck error FS3099: 'text' is used with an incorrect number of arguments. This is a custom operation in this query or computation expression. Expected 0 argument(s), but given 1.
 diff between [D:\workspace\_work\1\s\tests\fsharp\typecheck\sigs\neg60.bsl] and [D:\workspace\_work\1\s\tests\fsharp\typecheck\sigs\neg60.err]
 diff at line 191
 + 
 + neg60.fs(186,9,186,24): typecheck error FS3099: 'with_validators' is used with an incorrect number of arguments. This is a custom operation in this query or computation expression. Expected 0 argument(s), but given 2.
 + 
 + neg60.fs(194,9,194,17): typecheck error FS3099: 'password' is used with an incorrect number of arguments. This is a custom operation in this query or computation expression. Expected 0 argument(s), but given 1.
 + 
 + neg60.fs(195,9,195,24): typecheck error FS3099: 'with_validators' is used with an incorrect number of arguments. This is a custom operation in this query or computation expression. Expected 0 argument(s), but given 3.
 
 New error file:
 

````

**Comment by dsyme** [comment]
OK should be good to go now
